// AUTO-GENERATED by scripts/gen-recipes.ts — do not edit. Run `npm run gen`.
import type { RecipeMeta } from '../types'

export const RECIPE_INDEX: RecipeMeta[] = [
  {
    "slug": "bulk-utm-link-builder",
    "name": "Add UTM parameters to a list of URLs",
    "summary": "Paste a list of links, spreadsheet cells, a draft or HTML and get every URL tagged with the same utm_source, utm_medium and utm_campaign: old tags replaced, ? or & chosen per link, #anchors kept working.",
    "category": "Writing & Marketing",
    "utilityIds": [
      "extract_preset",
      "line_dedupe",
      "multi_replace",
      "sed"
    ],
    "chain": [
      "pull out the links",
      "remove old utm_ tags",
      "deduplicate lines",
      "add ? or & before any #",
      "your UTM values"
    ],
    "stepCount": 5,
    "published": "2026-10-07"
  },
  {
    "slug": "clean-chatgpt-text",
    "name": "Remove ChatGPT formatting from copied text",
    "summary": "Paste a ChatGPT answer and get plain text for an email, post or CMS: Markdown symbols gone, list numbers and bullets kept, and em dashes, curly quotes and hidden characters replaced.",
    "category": "Writing & Marketing",
    "utilityIds": [
      "collapse_whitespace",
      "markdown_strip",
      "multi_replace",
      "remove_invisible",
      "sed",
      "smart_quotes"
    ],
    "chain": [
      "invisible characters",
      "no-break spaces to plain spaces",
      "keep lists, tables and labels readable",
      "strip markdown",
      "replace em and en dashes",
      "straighten quotes"
    ],
    "stepCount": 6,
    "published": "2026-10-07"
  },
  {
    "slug": "decode-cloudwatch-logs-data",
    "name": "Decode CloudWatch Logs subscription data",
    "summary": "Paste a Lambda event with awslogs.data, a Kinesis or Firehose record, or the bare Base64 value, and read the log events inside as plain lines, with the gzip, the JSON envelope and the escapes undone.",
    "category": "Web & APIs",
    "utilityIds": [
      "code_string_unescape",
      "gzip_decompress",
      "json_to_jsonl",
      "jsonpath",
      "sed"
    ],
    "chain": [
      "pick the data field",
      "gzip decompress",
      "keep each message",
      "json to jsonl",
      "join into one string",
      "code string unescape"
    ],
    "stepCount": 6,
    "published": "2026-10-07"
  },
  {
    "slug": "decode-flask-session-cookie",
    "name": "Decode a Flask session cookie",
    "summary": "Paste a Flask session cookie, or the Cookie or Set-Cookie header carrying it, and read the session data inside as formatted JSON, compressed or not.",
    "category": "Web & APIs",
    "utilityIds": [
      "base64url_decode",
      "deflate_decompress",
      "json_pretty",
      "sed"
    ],
    "chain": [
      "sed script",
      "base64url decode",
      "deflate decompress",
      "json pretty"
    ],
    "stepCount": 4,
    "published": "2026-10-07"
  },
  {
    "slug": "decode-helm-release-secret",
    "name": "Decode a Helm release Secret",
    "summary": "Paste a Helm 3 release Secret from kubectl get secret -o yaml, or just its data.release value, and read the user-supplied values and the rendered manifest that helm get values and helm get manifest would show.",
    "category": "DevOps & Config",
    "utilityIds": [
      "base64_decode",
      "gzip_decompress",
      "insert_at",
      "json_to_yaml",
      "jsonpath",
      "yaml_to_json"
    ],
    "chain": [
      "yaml to json",
      "keep data.release",
      "remove the Kubernetes Base64 layer",
      "gzip decompress",
      "values and manifest"
    ],
    "stepCount": 5,
    "published": "2026-10-07"
  },
  {
    "slug": "decode-kubernetes-secret",
    "name": "Decode a Kubernetes Secret",
    "summary": "Paste a Secret from kubectl get secret -o yaml or -o json and read every value under data in plain text, with the keys kept, instead of decoding each one with base64 by hand.",
    "category": "DevOps & Config",
    "utilityIds": [
      "base64_decode",
      "jsonpath",
      "yaml_to_json"
    ],
    "chain": [
      "yaml to json",
      "keep data",
      "decode every value"
    ],
    "stepCount": 3,
    "published": "2026-10-07"
  },
  {
    "slug": "decode-saml-request",
    "name": "Decode a SAML request or response",
    "summary": "Paste a SAML redirect URL, a POST form body, a copied cURL command or a bare SAMLRequest or SAMLResponse value and read the message as indented XML, deflated (Redirect binding) or not (POST).",
    "category": "Web & APIs",
    "utilityIds": [
      "base64url_decode",
      "deflate_decompress",
      "sed",
      "url_decode",
      "xml_pretty"
    ],
    "chain": [
      "keep the SAML value",
      "url decode",
      "base64url decode",
      "deflate decompress",
      "xml pretty"
    ],
    "stepCount": 5,
    "published": "2026-10-07"
  },
  {
    "slug": "excel-column-to-sql-in-clause",
    "name": "Turn an Excel column into a SQL IN clause",
    "summary": "Paste a column copied from Excel or Google Sheets and get a ready-to-run IN (…) list: whitespace trimmed, duplicates dropped, apostrophes escaped and every value quoted.",
    "category": "Data & Spreadsheets",
    "utilityIds": [
      "line_affix",
      "line_dedupe",
      "sql_escape",
      "trim_lines"
    ],
    "chain": [
      "trim each line",
      "deduplicate lines",
      "sql escape",
      "quote and join values",
      "wrap in IN ( … )"
    ],
    "stepCount": 5,
    "published": "2026-10-07"
  },
  {
    "slug": "fix-bash-bad-interpreter",
    "name": "Fix ^M bad interpreter errors in a shell script",
    "summary": "Paste a script that fails with ^M: bad interpreter or $'\\r': command not found and get it back with LF line endings, no BOM or zero-width characters, plain spaces in place of no-break ones and no trailing whitespace.",
    "category": "DevOps & Config",
    "utilityIds": [
      "normalize_line_endings",
      "remove_invisible",
      "replace",
      "trim_lines"
    ],
    "chain": [
      "remove BOM and zero-width characters",
      "Unicode spaces to plain spaces",
      "normalize line endings",
      "trim trailing whitespace"
    ],
    "stepCount": 4,
    "published": "2026-10-07"
  },
  {
    "slug": "fix-pdf-line-breaks",
    "name": "Fix line breaks in text copied from a PDF",
    "summary": "Paste text copied from a PDF and get running text back: broken lines joined, hyphenated words rejoined, page numbers removed and ligature characters spelled out, with blank-line paragraph breaks and list items kept.",
    "category": "Writing & Marketing",
    "utilityIds": [
      "collapse_whitespace",
      "multi_replace",
      "normalize_line_endings",
      "sed",
      "unwrap"
    ],
    "chain": [
      "normalize line endings",
      "expand ligatures",
      "delete page numbers",
      "rejoin hyphenated words",
      "unwrap / reflow",
      "collapse whitespace"
    ],
    "stepCount": 6,
    "published": "2026-10-07"
  },
  {
    "slug": "nested-json-to-csv",
    "name": "Convert nested JSON to CSV",
    "summary": "Paste an API response or a JSON array and get a spreadsheet-ready CSV: the records picked out of their envelope, nested objects and arrays spread into columns of their own, and headers renamed to snake_case.",
    "category": "Data & Spreadsheets",
    "utilityIds": [
      "csv_normalize_headers",
      "json_to_csv",
      "jsonpath"
    ],
    "chain": [
      "select the records",
      "json to csv",
      "csv normalize headers"
    ],
    "stepCount": 3,
    "published": "2026-10-07"
  },
  {
    "slug": "spring-boot-yaml-to-env-vars",
    "name": "Convert Spring Boot application.yml to environment variables",
    "summary": "Paste an application.yml and get the environment variable names Spring Boot's relaxed binding expects: dots to underscores, dashes removed, list indexes kept, as .env lines and a Kubernetes env: list.",
    "category": "DevOps & Config",
    "utilityIds": [
      "json_to_env",
      "jsonpath",
      "sed",
      "yaml_to_json"
    ],
    "chain": [
      "parse application.yml",
      "keep the first document",
      "remove dashes from keys",
      ".env and Kubernetes env:"
    ],
    "stepCount": 4,
    "published": "2026-10-07"
  },
  {
    "slug": "unescape-stringified-json",
    "name": "Unescape stringified JSON and pretty-print it",
    "summary": "Paste JSON full of backslashes, quoted or not, stringified once or twice, and get indented JSON back. Text that is already valid JSON is only pretty-printed.",
    "category": "Frontend",
    "utilityIds": [
      "code_string_unescape",
      "json_pretty",
      "trim"
    ],
    "chain": [
      "trim",
      "unescape one layer",
      "unescape a second layer",
      "json pretty"
    ],
    "stepCount": 4,
    "published": "2026-10-07"
  }
]
