// AUTO-GENERATED by scripts/gen-recipes.ts — do not edit. Run `npm run gen`.
import type { RecipeMeta } from '../types'

export const RECIPE_INDEX: RecipeMeta[] = [
  {
    "slug": "bulk-utm-link-builder",
    "name": "Add UTM parameters to a list of URLs",
    "summary": "Paste a list of links, spreadsheet cells, a draft or HTML and get every URL tagged with the same utm_source, utm_medium and utm_campaign: old tags replaced, ? or & chosen per link, #anchors kept working.",
    "category": "Writing & Marketing",
    "utilityIds": [
      "extract_preset",
      "line_dedupe",
      "multi_replace",
      "query_params_normalize",
      "sed",
      "unescape_html"
    ],
    "chain": [
      "pull out the links",
      "remove old utm_ tags",
      "deduplicate lines",
      "add ? or & before any #",
      "your UTM values"
    ],
    "stepCount": 5,
    "published": "2026-10-07",
    "updated": "2026-10-08"
  },
  {
    "slug": "clean-chatgpt-text",
    "name": "Remove ChatGPT formatting from copied text",
    "summary": "Paste a ChatGPT answer and get plain text for an email, post or CMS: Markdown symbols gone, list numbers and bullets kept, and em dashes, curly quotes and hidden characters replaced.",
    "category": "Writing & Marketing",
    "utilityIds": [
      "collapse_whitespace",
      "markdown_strip",
      "multi_replace",
      "remove_invisible",
      "sed",
      "smart_quotes"
    ],
    "chain": [
      "invisible characters",
      "no-break spaces to plain spaces",
      "keep lists, tables and labels readable",
      "strip markdown",
      "replace em and en dashes",
      "straighten quotes"
    ],
    "stepCount": 6,
    "published": "2026-10-07"
  },
  {
    "slug": "clean-text-pasted-from-word",
    "name": "Clean up text pasted from Microsoft Word",
    "summary": "Paste text copied out of a Word document and get plain text that behaves: curly quotes and dashes undone, list bullets turned into hyphens, hidden hyphens and no-break spaces gone.",
    "category": "Writing & Marketing",
    "utilityIds": [
      "collapse_whitespace",
      "multi_replace",
      "remove_invisible",
      "sed",
      "smart_quotes"
    ],
    "chain": [
      "hidden characters",
      "spaces and blank lines",
      "bullets and numbered items",
      "dashes back to hyphens",
      "straight quotes"
    ],
    "stepCount": 5,
    "published": "2026-10-09"
  },
  {
    "slug": "convert-unix-timestamps-in-json",
    "name": "Convert Unix timestamps in a JSON response to dates",
    "summary": "Paste an API response and get the same JSON back with its epoch seconds and milliseconds turned into ISO 8601 dates at any depth, while small ids, prices and phone numbers stay as they are.",
    "category": "Web & APIs",
    "utilityIds": [
      "json_flatten",
      "json_unflatten",
      "timestamp_convert"
    ],
    "chain": [
      "flatten to paths",
      "convert epoch values",
      "rebuild the JSON"
    ],
    "stepCount": 3,
    "published": "2026-10-08"
  },
  {
    "slug": "decode-cloudwatch-logs-data",
    "name": "Decode CloudWatch Logs subscription data",
    "summary": "Paste a Lambda event with awslogs.data, a Kinesis or Firehose batch, or the bare Base64 value, and read the log events of every record as plain lines, with the gzip, the JSON envelope and the escapes undone.",
    "category": "Web & APIs",
    "utilityIds": [
      "code_string_unescape",
      "gzip_decompress",
      "json_to_jsonl",
      "jsonpath",
      "normalize_line_endings",
      "regex_extract"
    ],
    "chain": [
      "find every payload",
      "unzip each payload",
      "keep each message",
      "decode each message"
    ],
    "stepCount": 4,
    "published": "2026-10-07",
    "updated": "2026-10-08"
  },
  {
    "slug": "decode-flask-session-cookie",
    "name": "Decode a Flask session cookie",
    "summary": "Paste a Flask session cookie, or the Cookie or Set-Cookie header carrying it, and read the session data inside as formatted JSON, compressed or not.",
    "category": "Web & APIs",
    "utilityIds": [
      "base64url_decode",
      "deflate_decompress",
      "json_pretty",
      "sed"
    ],
    "chain": [
      "sed script",
      "base64url decode",
      "deflate decompress",
      "json pretty"
    ],
    "stepCount": 4,
    "published": "2026-10-07"
  },
  {
    "slug": "decode-helm-release-secret",
    "name": "Decode a Helm release Secret",
    "summary": "Paste a Helm 3 release Secret from kubectl get secret -o yaml, or just its data.release value, and read the user-supplied values and the rendered manifest that helm get values and helm get manifest would show.",
    "category": "DevOps & Config",
    "utilityIds": [
      "base64_decode",
      "gzip_decompress",
      "insert_at",
      "json_to_yaml",
      "jsonpath",
      "yaml_to_json"
    ],
    "chain": [
      "yaml to json",
      "keep data.release",
      "remove the Kubernetes Base64 layer",
      "gzip decompress",
      "values and manifest"
    ],
    "stepCount": 5,
    "published": "2026-10-07"
  },
  {
    "slug": "decode-jwts-in-log-file",
    "name": "Decode every JWT in a log or HAR file",
    "summary": "Paste a log, a HAR export or a curl -v trace and read the claims of every JSON Web Token in it, each once, with iat, exp and auth_time shown as dates instead of epoch seconds.",
    "category": "Web & APIs",
    "utilityIds": [
      "extract_preset",
      "jsonl_to_json",
      "jwt_decode",
      "timestamp_convert"
    ],
    "chain": [
      "find every token",
      "decode each token",
      "one JSON array"
    ],
    "stepCount": 3,
    "published": "2026-10-08"
  },
  {
    "slug": "decode-kubernetes-secret",
    "name": "Decode a Kubernetes Secret",
    "summary": "Paste a Secret from kubectl get secret -o yaml or -o json and read every value under data in plain text, with the keys kept, instead of decoding each one with base64 by hand.",
    "category": "DevOps & Config",
    "utilityIds": [
      "base64_decode",
      "jsonpath",
      "yaml_to_json"
    ],
    "chain": [
      "yaml to json",
      "keep data",
      "decode every value"
    ],
    "stepCount": 3,
    "published": "2026-10-07"
  },
  {
    "slug": "decode-saml-request",
    "name": "Decode a SAML request or response",
    "summary": "Paste a SAML redirect URL, a POST form body, a copied cURL command or a bare SAMLRequest or SAMLResponse value and read the message as indented XML, deflated (Redirect binding) or not (POST).",
    "category": "Web & APIs",
    "utilityIds": [
      "base64url_decode",
      "deflate_decompress",
      "sed",
      "url_decode",
      "xml_pretty"
    ],
    "chain": [
      "keep the SAML value",
      "url decode",
      "base64url decode",
      "deflate decompress",
      "xml pretty"
    ],
    "stepCount": 5,
    "published": "2026-10-07"
  },
  {
    "slug": "env-file-to-kubernetes-secret",
    "name": "Turn a .env file into a Kubernetes Secret",
    "summary": "Paste a .env file and get a Secret manifest with every value Base64-encoded under data, ready for kubectl apply, with quotes, export prefixes, comments and multi-line values handled.",
    "category": "DevOps & Config",
    "utilityIds": [
      "base64_encode",
      "env_to_json",
      "json_to_yaml",
      "replace"
    ],
    "chain": [
      "parse the .env file",
      "encode every value",
      "wrap in a Secret",
      "json to yaml"
    ],
    "stepCount": 4,
    "published": "2026-10-08"
  },
  {
    "slug": "excel-column-to-sql-in-clause",
    "name": "Turn an Excel column into a SQL IN clause",
    "summary": "Paste a column copied from Excel or Google Sheets and get a ready-to-run IN (…) list: whitespace trimmed, duplicates dropped, and every value escaped and quoted for your SQL dialect.",
    "category": "Data & Spreadsheets",
    "utilityIds": [
      "line_affix",
      "line_dedupe",
      "sql_escape",
      "trim_lines"
    ],
    "chain": [
      "trim each line",
      "deduplicate lines",
      "quote each value",
      "join with commas",
      "wrap in IN ( … )"
    ],
    "stepCount": 5,
    "published": "2026-10-07",
    "updated": "2026-10-08"
  },
  {
    "slug": "extract-domains-from-urls",
    "name": "Extract the domain from a list of URLs",
    "summary": "Paste a column of links and get each one’s hostname on the same line, lowercased and without www., whether or not the link starts with https://, so it pastes back beside its URL.",
    "category": "Data & Spreadsheets",
    "utilityIds": [
      "jsonpath",
      "line_affix",
      "replace",
      "url_parse"
    ],
    "chain": [
      "hostname of every URL",
      "drop www."
    ],
    "stepCount": 2,
    "published": "2026-10-08"
  },
  {
    "slug": "extract-unique-emails-from-text",
    "name": "Extract unique email addresses from text",
    "summary": "Paste an email thread, a CSV export or a contact page and get each address once: matched in any surrounding text, lower-cased so case variants count as one, sorted, and with no-reply senders left out.",
    "category": "Data & Spreadsheets",
    "utilityIds": [
      "case",
      "extract_preset",
      "grep_lines"
    ],
    "chain": [
      "lower-case",
      "pull out unique addresses",
      "leave out no-reply senders"
    ],
    "stepCount": 3,
    "published": "2026-10-09"
  },
  {
    "slug": "fix-bash-bad-interpreter",
    "name": "Fix ^M bad interpreter errors in a shell script",
    "summary": "Paste a script that fails with ^M: bad interpreter or $'\\r': command not found and get it back with LF line endings, no BOM or zero-width characters, plain spaces in place of no-break ones and no trailing whitespace.",
    "category": "DevOps & Config",
    "utilityIds": [
      "normalize_line_endings",
      "remove_invisible",
      "replace",
      "trim_lines"
    ],
    "chain": [
      "remove BOM and zero-width characters",
      "Unicode spaces to plain spaces",
      "normalize line endings",
      "trim trailing whitespace"
    ],
    "stepCount": 4,
    "published": "2026-10-07"
  },
  {
    "slug": "fix-pdf-line-breaks",
    "name": "Fix line breaks in text copied from a PDF",
    "summary": "Paste text copied from a PDF and get running text back: broken lines joined, hyphenated words rejoined, page numbers removed and ligature characters spelled out, with blank-line paragraph breaks and list items kept.",
    "category": "Writing & Marketing",
    "utilityIds": [
      "collapse_whitespace",
      "multi_replace",
      "normalize_line_endings",
      "sed",
      "unwrap"
    ],
    "chain": [
      "normalize line endings",
      "expand ligatures",
      "delete page numbers",
      "rejoin hyphenated words",
      "unwrap / reflow",
      "collapse whitespace"
    ],
    "stepCount": 6,
    "published": "2026-10-07"
  },
  {
    "slug": "hash-email-list-for-customer-match",
    "name": "Hash an email list for Customer Match",
    "summary": "Paste a column of customer emails and get one SHA-256 hash per line, normalized the way Google Ads Customer Match expects, with header and blank rows kept so rows still line up.",
    "category": "Writing & Marketing",
    "utilityIds": [
      "case",
      "hash",
      "replace"
    ],
    "chain": [
      "remove spaces and quotes",
      "change case",
      "drop Gmail dots",
      "SHA-256 every address"
    ],
    "stepCount": 4,
    "published": "2026-10-08"
  },
  {
    "slug": "nested-json-to-csv",
    "name": "Convert nested JSON to CSV",
    "summary": "Paste an API response or a JSON array and get a spreadsheet-ready CSV: the records picked out of their envelope, nested objects and arrays spread into columns of their own, and headers renamed to snake_case.",
    "category": "Data & Spreadsheets",
    "utilityIds": [
      "csv_normalize_headers",
      "json_to_csv",
      "jsonpath"
    ],
    "chain": [
      "select the records",
      "json to csv",
      "csv normalize headers"
    ],
    "stepCount": 3,
    "published": "2026-10-07"
  },
  {
    "slug": "parse-user-agents-from-access-log",
    "name": "Parse user agents from an access log into a CSV",
    "summary": "Paste nginx or Apache access log lines, or a column of user-agent strings, and get a CSV row per line with the browser, OS, device and a bot flag.",
    "category": "Web & APIs",
    "utilityIds": [
      "json_to_csv",
      "jsonl_to_json",
      "replace",
      "user_agent_parse"
    ],
    "chain": [
      "keep the user-agent field",
      "parse every line",
      "collect into an array",
      "pick columns as CSV"
    ],
    "stepCount": 4,
    "published": "2026-10-08"
  },
  {
    "slug": "remove-tracking-parameters-from-urls",
    "name": "Remove tracking parameters from a list of URLs",
    "summary": "Paste links one per line and get them back without utm_ tags, fbclid, gclid, srsltid and other click ids, with the parameters a page needs, the order and any #anchor kept.",
    "category": "Writing & Marketing",
    "utilityIds": [
      "query_params_normalize",
      "unescape_html"
    ],
    "chain": [
      "undo &amp;",
      "clean every link"
    ],
    "stepCount": 2,
    "published": "2026-10-08"
  },
  {
    "slug": "spring-boot-yaml-to-env-vars",
    "name": "Convert Spring Boot application.yml to environment variables",
    "summary": "Paste an application.yml and get the environment variable names Spring Boot's relaxed binding expects: dots to underscores, dashes removed, list indexes kept, as .env lines and a Kubernetes env: list.",
    "category": "DevOps & Config",
    "utilityIds": [
      "json_to_env",
      "jsonpath",
      "sed",
      "yaml_to_json"
    ],
    "chain": [
      "parse application.yml",
      "keep the first document",
      "remove dashes from keys",
      ".env and Kubernetes env:"
    ],
    "stepCount": 4,
    "published": "2026-10-07"
  },
  {
    "slug": "unescape-stringified-json",
    "name": "Unescape stringified JSON and pretty-print it",
    "summary": "Paste JSON full of backslashes, quoted or not, stringified once or twice, and get indented JSON back. Text that is already valid JSON is only pretty-printed.",
    "category": "Frontend",
    "utilityIds": [
      "code_string_unescape",
      "json_pretty",
      "trim"
    ],
    "chain": [
      "trim",
      "unescape one layer",
      "unescape a second layer",
      "json pretty"
    ],
    "stepCount": 4,
    "published": "2026-10-07"
  }
]
