// AUTO-GENERATED by scripts/gen-recipes.ts — do not edit. Run `npm run gen`.
import type { RecipeMeta } from '../types'

export const RECIPE_INDEX: RecipeMeta[] = [
  {
    "slug": "excel-column-to-sql-in-clause",
    "name": "Turn an Excel column into a SQL IN clause",
    "summary": "Paste a column copied from Excel or Google Sheets and get a ready-to-run IN (…) list: whitespace trimmed, duplicates dropped, apostrophes escaped and every value quoted.",
    "category": "Data & Spreadsheets",
    "utilityIds": [
      "line_affix",
      "line_dedupe",
      "sql_escape",
      "trim_lines"
    ],
    "chain": [
      "trim each line",
      "deduplicate lines",
      "sql escape",
      "quote and join values",
      "wrap in IN ( … )"
    ],
    "stepCount": 5,
    "published": "2026-10-07"
  }
]
