// AUTO-GENERATED by scripts/gen-recipes.ts — do not edit. Run `npm run gen`.
import type { Recipe } from '../types'
import r0 from '../excel-column-to-sql-in-clause/recipe'

export const STATIC_RECIPES: Recipe[] = [
  r0,
]
