// AUTO-GENERATED by scripts/gen-recipes.ts — do not edit. Run `npm run gen`.
import type { Recipe } from '../types'
import r0 from '../bulk-utm-link-builder/recipe'
import r1 from '../clean-chatgpt-text/recipe'
import r2 from '../clean-text-pasted-from-word/recipe'
import r3 from '../convert-unix-timestamps-in-json/recipe'
import r4 from '../decode-cloudwatch-logs-data/recipe'
import r5 from '../decode-flask-session-cookie/recipe'
import r6 from '../decode-helm-release-secret/recipe'
import r7 from '../decode-jwts-in-log-file/recipe'
import r8 from '../decode-kubernetes-secret/recipe'
import r9 from '../decode-saml-request/recipe'
import r10 from '../env-file-to-kubernetes-secret/recipe'
import r11 from '../excel-column-to-sql-in-clause/recipe'
import r12 from '../extract-domains-from-urls/recipe'
import r13 from '../extract-unique-emails-from-text/recipe'
import r14 from '../fix-bash-bad-interpreter/recipe'
import r15 from '../fix-pdf-line-breaks/recipe'
import r16 from '../hash-email-list-for-customer-match/recipe'
import r17 from '../nested-json-to-csv/recipe'
import r18 from '../parse-user-agents-from-access-log/recipe'
import r19 from '../remove-tracking-parameters-from-urls/recipe'
import r20 from '../spring-boot-yaml-to-env-vars/recipe'
import r21 from '../unescape-stringified-json/recipe'

export const STATIC_RECIPES: Recipe[] = [
  r0,
  r1,
  r2,
  r3,
  r4,
  r5,
  r6,
  r7,
  r8,
  r9,
  r10,
  r11,
  r12,
  r13,
  r14,
  r15,
  r16,
  r17,
  r18,
  r19,
  r20,
  r21,
]
