// AUTO-GENERATED by scripts/gen-presets.ts — do not edit. Run `npm run gen`.
import type { Preset } from '../types'

/** One chunk per preset: its definition and its guide markdown. */
export const PRESET_LOADERS: Record<string, () => Promise<{ preset: Preset; guide: string }>> = {
  "bulk-utm-link-builder": () => Promise.all([import('../bulk-utm-link-builder/preset'), import('../bulk-utm-link-builder/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "clean-chatgpt-text": () => Promise.all([import('../clean-chatgpt-text/preset'), import('../clean-chatgpt-text/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "clean-text-pasted-from-word": () => Promise.all([import('../clean-text-pasted-from-word/preset'), import('../clean-text-pasted-from-word/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "convert-unix-timestamps-in-json": () => Promise.all([import('../convert-unix-timestamps-in-json/preset'), import('../convert-unix-timestamps-in-json/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "decode-cloudwatch-logs-data": () => Promise.all([import('../decode-cloudwatch-logs-data/preset'), import('../decode-cloudwatch-logs-data/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "decode-flask-session-cookie": () => Promise.all([import('../decode-flask-session-cookie/preset'), import('../decode-flask-session-cookie/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "decode-helm-release-secret": () => Promise.all([import('../decode-helm-release-secret/preset'), import('../decode-helm-release-secret/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "decode-jwts-in-log-file": () => Promise.all([import('../decode-jwts-in-log-file/preset'), import('../decode-jwts-in-log-file/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "decode-kubernetes-secret": () => Promise.all([import('../decode-kubernetes-secret/preset'), import('../decode-kubernetes-secret/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "decode-saml-request": () => Promise.all([import('../decode-saml-request/preset'), import('../decode-saml-request/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "env-file-to-kubernetes-secret": () => Promise.all([import('../env-file-to-kubernetes-secret/preset'), import('../env-file-to-kubernetes-secret/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "excel-column-to-sql-in-clause": () => Promise.all([import('../excel-column-to-sql-in-clause/preset'), import('../excel-column-to-sql-in-clause/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "extract-domains-from-urls": () => Promise.all([import('../extract-domains-from-urls/preset'), import('../extract-domains-from-urls/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "extract-unique-emails-from-text": () => Promise.all([import('../extract-unique-emails-from-text/preset'), import('../extract-unique-emails-from-text/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "fix-bash-bad-interpreter": () => Promise.all([import('../fix-bash-bad-interpreter/preset'), import('../fix-bash-bad-interpreter/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "fix-pdf-line-breaks": () => Promise.all([import('../fix-pdf-line-breaks/preset'), import('../fix-pdf-line-breaks/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "hash-email-list-for-customer-match": () => Promise.all([import('../hash-email-list-for-customer-match/preset'), import('../hash-email-list-for-customer-match/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "nested-json-to-csv": () => Promise.all([import('../nested-json-to-csv/preset'), import('../nested-json-to-csv/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "parse-user-agents-from-access-log": () => Promise.all([import('../parse-user-agents-from-access-log/preset'), import('../parse-user-agents-from-access-log/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "remove-tracking-parameters-from-urls": () => Promise.all([import('../remove-tracking-parameters-from-urls/preset'), import('../remove-tracking-parameters-from-urls/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "spring-boot-yaml-to-env-vars": () => Promise.all([import('../spring-boot-yaml-to-env-vars/preset'), import('../spring-boot-yaml-to-env-vars/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
  "unescape-stringified-json": () => Promise.all([import('../unescape-stringified-json/preset'), import('../unescape-stringified-json/guide.md?raw')]).then(([r, g]) => ({ preset: r.default, guide: g.default })),
}
