// AUTO-GENERATED by scripts/gen-presets.ts — do not edit. Run `npm run gen`.
import type { Preset } from '../types'
import r0 from '../bulk-utm-link-builder/preset'
import r1 from '../clean-chatgpt-text/preset'
import r2 from '../clean-text-pasted-from-word/preset'
import r3 from '../convert-unix-timestamps-in-json/preset'
import r4 from '../decode-cloudwatch-logs-data/preset'
import r5 from '../decode-flask-session-cookie/preset'
import r6 from '../decode-helm-release-secret/preset'
import r7 from '../decode-jwts-in-log-file/preset'
import r8 from '../decode-kubernetes-secret/preset'
import r9 from '../decode-saml-request/preset'
import r10 from '../env-file-to-kubernetes-secret/preset'
import r11 from '../excel-column-to-sql-in-clause/preset'
import r12 from '../extract-domains-from-urls/preset'
import r13 from '../extract-unique-emails-from-text/preset'
import r14 from '../fix-bash-bad-interpreter/preset'
import r15 from '../fix-pdf-line-breaks/preset'
import r16 from '../hash-email-list-for-customer-match/preset'
import r17 from '../nested-json-to-csv/preset'
import r18 from '../parse-user-agents-from-access-log/preset'
import r19 from '../remove-tracking-parameters-from-urls/preset'
import r20 from '../spring-boot-yaml-to-env-vars/preset'
import r21 from '../unescape-stringified-json/preset'

export const STATIC_PRESETS: Preset[] = [
  r0,
  r1,
  r2,
  r3,
  r4,
  r5,
  r6,
  r7,
  r8,
  r9,
  r10,
  r11,
  r12,
  r13,
  r14,
  r15,
  r16,
  r17,
  r18,
  r19,
  r20,
  r21,
]
