import { run } from '../../harness'
import { toPipelineSteps } from '/home/user/string-utility-belt/src/recipes/types'
// import the draft without re-running proto: copy recipe via dynamic import side effects is fine (prints once)
const { recipe } = await import(process.env.DRAFT ?? '../strip-tracking')
const steps = toPipelineSteps(recipe.steps)
const show = async (label: string, input: string) => {
  const r = await run(input, steps)
  console.log(`\n# ${label}\nIN  ${JSON.stringify(input)}\nOUT ${JSON.stringify(r.out)}${Object.keys(r.errors).length ? '  ERR ' + JSON.stringify(r.errors) : ''}`)
}
console.log('\n\n================ ADVERSARIAL')
await show('CSV row url,clicks', 'url,clicks\nhttps://shop.example.com/p?id=1&utm_source=x,42\nhttps://shop.example.com/q?utm_source=x&id=2,17')
await show('quoted CSV cell', '"https://a.example.com/?id=1&utm_source=x"')
await show('angle brackets', '<https://a.example.com/?id=1&utm_source=x>')
await show('markdown link, no-space text', '[docs](https://a.example.com/?id=1&utm_source=x)')
await show('markdown link with spaces', '[read the docs](https://a.example.com/?id=1&utm_source=x)')
await show('HTML attribute line', '  href="https://a.example.com/?id=1&amp;utm_source=x"\n<a href="https://b.example.com/?utm_source=y&amp;id=2">Shop</a>')
await show('TSV row (spreadsheet paste)', 'https://a.example.com/?srsltid=AfmBOo123\t1,234\t5.2%')
await show('trailing period / paren', 'https://a.example.com/?id=1&utm_source=x.\n(https://a.example.com/?id=1&utm_source=x)')
await show('JSON array of urls', '["https://a.example.com/?utm_source=x&id=1","https://b.example.com/?fbclid=1"]')
await show('google redirect wrapper', 'https://www.google.com/url?q=https://www.example.com/page?utm_source%3Dx&sa=D&source=editors&ust=1&usg=AOv')
await show('youtube si + feature', 'https://youtu.be/dQw4w9WgXcQ?si=AbCdEfGh123\nhttps://www.youtube.com/watch?v=dQw4w9WgXcQ&feature=share&pp=ygU')
await show('klaviyo/kit/drip/ga', 'https://shop.example.com/?_kx=abc.def&id=1\nhttps://shop.example.com/?ck_subscriber_id=123&id=2\nhttps://shop.example.com/?__s=xyz&id=3\nhttps://shop.example.com/?_ga=2.1234.5678&id=4')
await show('BOM + NBSP', '﻿https://a.example.com/?utm_source=x&id=1 \nhttps://b.example.com/?id=2&gclid=z')
await show('heading with &amp;', 'Tom &amp; Jerry &lt;links&gt;\nhttps://a.example.com/?id=1&amp;utm_source=x')
await show('&amp; with HTML numeric &#38;', 'https://a.example.com/?id=1&#38;utm_source=x')
await show('trailing ? only and leading &', 'https://a.example.com/?\nhttps://a.example.com/?&utm_source=x&id=1')
await show('plus-encoded spaces and %26', 'https://a.example.com/search?q=tom%26jerry+dvd&utm_source=x')
await show('line with only ? word', 'Q?A\nfoo?utm_source\nWhat?Why')
await show('url with port and userinfo', 'https://user:pw@A.Example.com:8443/Path?utm_source=x&ID=1')
await show('long query (2k)', 'https://a.example.com/?' + Array.from({ length: 200 }, (_, i) => `k${i}=v${i}`).join('&') + '&utm_source=x')
await show('scheme-less www and uppercase scheme', 'www.example.com/page?utm_source=x&id=1\nHTTPS://WWW.EXAMPLE.COM/?gclid=1&id=2\nexample.com/page?utm_source=x')
await show('wikipedia parens in path', 'https://en.example.org/wiki/Foo_(bar)?utm_source=x')
await show('comma in query value', 'https://a.example.com/?fields=a,b&utm_source=x')
