/**
 * Generates the recipe index and loaders from `src/recipes/<slug>/recipe.ts`
 * (run by `npm run gen`, after the utility manifest it reads).
 *
 * Outputs (src/recipes/_generated/, committed; `npm test` fails if stale):
 *   index.ts    — `RecipeMeta` for every recipe: names, chains, utility ids (no steps or samples)
 *   loaders.ts  — `slug → () => import(...)`: one lazy chunk per recipe, its guide included (browser)
 *   static.ts   — static imports of every recipe (Node: the SEO build, tests, scripts)
 *
 * Run with vite-node so TypeScript and the `@/` alias resolve exactly as in the app.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { MANIFEST } from '../src/utilities/_generated/manifest'
import { countSteps, isBranchStep, isMacroStep, isUtilityStep, utilityIds } from '../src/core/steps'
import { displayName } from '../src/app/pages/seo'
import { toPipelineSteps, type Recipe, type RecipeMeta } from '../src/recipes/types'

const ROOT = process.cwd()
const RECIPE_DIR = path.join(ROOT, 'src', 'recipes')
const OUT_DIR = path.join(RECIPE_DIR, '_generated')
const HEADER = '// AUTO-GENERATED by scripts/gen-recipes.ts — do not edit. Run `npm run gen`.\n'

/** Recipe folders: every directory with a `recipe.ts` (`_generated` and dot-folders aside). */
export function discoverRecipes(): string[] {
  return readdirSync(RECIPE_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory() && !d.name.startsWith('_') && !d.name.startsWith('.'))
    .map(d => d.name)
    .filter(dir => existsSync(path.join(RECIPE_DIR, dir, 'recipe.ts')))
    .sort()
}

/** Loads `src/recipes/<dir>/recipe.ts` (shared with `check-recipes`). */
export async function loadRecipe(dir: string): Promise<Recipe | undefined> {
  const mod = (await import(/* @vite-ignore */ `/src/recipes/${dir}/recipe.ts`)) as { default?: Recipe }
  return mod.default
}

/** `src/recipes/<dir>/guide.md`, or null. */
export function readRecipeGuide(dir: string): string | null {
  const file = path.join(RECIPE_DIR, dir, 'guide.md')
  return existsSync(file) ? readFileSync(file, 'utf8') : null
}

const names = new Map(MANIFEST.map(m => [m.id, displayName(m.name)]))

export function metaOfRecipe(recipe: Recipe): RecipeMeta {
  const steps = toPipelineSteps(recipe.steps)
  return {
    slug: recipe.slug,
    name: recipe.name,
    summary: recipe.summary,
    category: recipe.category,
    utilityIds: utilityIds(steps).sort(),
    chain: steps.map(s => isUtilityStep(s) ? names.get(s.utilityId) ?? s.utilityId
      : isBranchStep(s) ? `branch (${s.branches.length} lanes)`
        : isMacroStep(s) ? s.name : 'step'),
    stepCount: countSteps(steps),
    published: recipe.published,
    ...(recipe.updated ? { updated: recipe.updated } : {}),
  }
}

const ident = (i: number) => `r${i}`

/** Build every generated file's content in memory (no writes). */
export async function build(): Promise<{ count: number; files: Record<string, string> }> {
  const dirs = discoverRecipes()
  const metas: RecipeMeta[] = []
  const problems: string[] = []
  const known = new Set(MANIFEST.map(m => m.id))
  for (const dir of dirs) {
    const recipe = await loadRecipe(dir)
    if (!recipe || !Array.isArray(recipe.steps)) { problems.push(`${dir}: no recipe default export`); continue }
    if (recipe.slug !== dir) problems.push(`${dir}: slug "${recipe.slug}" must match its directory`)
    if (!existsSync(path.join(RECIPE_DIR, dir, 'guide.md'))) problems.push(`${dir}: missing guide.md`)
    const meta = metaOfRecipe(recipe)
    const unknown = meta.utilityIds.filter(id => !known.has(id))
    if (unknown.length) problems.push(`${dir}: unknown utilities ${unknown.join(', ')}`)
    metas.push(meta)
  }
  if (problems.length) throw new Error('recipe index problems:\n  ' + problems.join('\n  '))

  const files: Record<string, string> = {
    'index.ts':
      HEADER +
      "import type { RecipeMeta } from '../types'\n\n" +
      `export const RECIPE_INDEX: RecipeMeta[] = ${JSON.stringify(metas, null, 2)}\n`,
    'loaders.ts':
      HEADER +
      "import type { Recipe } from '../types'\n\n" +
      '/** One chunk per recipe: its definition and its guide markdown. */\n' +
      'export const RECIPE_LOADERS: Record<string, () => Promise<{ recipe: Recipe; guide: string }>> = {\n' +
      dirs.map(dir => `  ${JSON.stringify(dir)}: () => Promise.all([import('../${dir}/recipe'), import('../${dir}/guide.md?raw')])` +
        '.then(([r, g]) => ({ recipe: r.default, guide: g.default })),').join('\n') +
      '\n}\n',
    'static.ts':
      HEADER +
      "import type { Recipe } from '../types'\n" +
      dirs.map((dir, i) => `import ${ident(i)} from '../${dir}/recipe'`).join('\n') +
      '\n\nexport const STATIC_RECIPES: Recipe[] = [\n' +
      dirs.map((_, i) => `  ${ident(i)},`).join('\n') +
      '\n]\n',
  }
  return { count: metas.length, files }
}

function writeIfChanged(file: string, content: string): boolean {
  if (existsSync(file) && readFileSync(file, 'utf8') === content) return false
  writeFileSync(file, content)
  return true
}

/** Write the generated files, touching only those whose content changed. */
export async function generate(): Promise<{ count: number; written: string[] }> {
  const { count, files } = await build()
  mkdirSync(OUT_DIR, { recursive: true })
  const written: string[] = []
  for (const [name, content] of Object.entries(files)) {
    if (writeIfChanged(path.join(OUT_DIR, name), content)) written.push(name)
  }
  return { count, written }
}

export const RECIPES_GENERATED_DIR = OUT_DIR
export { RECIPE_DIR }
