/**
 * Generates the utility manifest and loaders from `src/utilities/<id>/index.ts`.
 *
 *   npm run gen          (runs automatically before `dev` and `build`)
 *
 * Outputs (src/utilities/_generated/, committed; `npm test` fails if stale):
 *   manifest.ts  — metadata for every utility, no code (ships in the initial bundle)
 *   examples.ts  — worked examples (loaded lazily by doc pages)
 *   loaders.ts   — `id → () => import(...)`: one lazy chunk per utility (browser)
 *   static.ts    — static imports of every utility (Node, Cloudflare Worker, CLI, MCP)
 *
 * Run with vite-node so TypeScript and the `@/` alias resolve exactly as in the app.
 */
import { readFileSync, readdirSync, existsSync, writeFileSync, mkdirSync } from 'node:fs'
import path from 'node:path'
import type { Utility, UtilityEnv, UtilityExample } from '../src/types/utility'
import { metaOf, type UtilityMeta } from '../src/core/registry'

const ROOT = process.cwd()
const UTIL_DIR = path.join(ROOT, 'src', 'utilities')
const OUT_DIR = path.join(UTIL_DIR, '_generated')
const HEADER = '// AUTO-GENERATED by scripts/gen-utilities.ts — do not edit. Run `npm run gen`.\n'

/**
 * Capabilities inferred from source text; a utility can also declare `env` itself.
 * API usage is matched against code with comments AND string literals removed, so
 * prose ("a YAML document.") and data ('word/document.xml') cannot match. Imports
 * are matched against the specifier strings, which is why they get their own list.
 */
const API_PATTERNS: Array<[UtilityEnv, RegExp]> = [
  ['dom', /\bnew\s+DOMParser\b|(^|[^.\w$])document\.[A-Za-z_$]|\bnew\s+XMLSerializer\b/],
  ['eval', /\bnew\s+Function\s*\(|(^|[^.\w$])eval\s*\(/],
]
const IMPORT_PATTERNS: Array<[UtilityEnv, RegExp]> = [
  ['dom', /\bimport\s*\(\s*['"]turndown['"]|\bfrom\s+['"]turndown['"]/],
  ['wasm', /\bimport\s*\(\s*['"]hash-wasm['"]|\bfrom\s+['"]hash-wasm['"]/],
]

/** Drop block and line comments (a `//` preceded by `:` is kept — it is a URL). */
export const stripComments = (src: string): string =>
  src.replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/(^|[^:\\])\/\/.*$/gm, '$1')

/** Blank out string and template literal contents. */
export const stripStrings = (src: string): string =>
  src.replace(/'(?:\\.|[^'\\\n])*'|"(?:\\.|[^"\\\n])*"|`(?:\\.|[^`\\])*`/g, '""')

export interface Discovered { dir: string; file: string; source: string }

export function discover(): Discovered[] {
  return readdirSync(UTIL_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory() && !d.name.startsWith('_') && !d.name.startsWith('.'))
    .map(d => {
      const ts = path.join(UTIL_DIR, d.name, 'index.ts')
      const tsx = path.join(UTIL_DIR, d.name, 'index.tsx')
      const file = existsSync(ts) ? ts : existsSync(tsx) ? tsx : ''
      return { dir: d.name, file, source: file ? readFileSync(file, 'utf8') : '' }
    })
    .filter(d => d.file)
    .sort((a, b) => a.dir.localeCompare(b.dir))
}

export const detectEnv = (source: string): UtilityEnv[] => {
  const withStrings = stripComments(source)
  const code = stripStrings(withStrings)
  // a utility that feature-tests DOMParser has a non-DOM fallback, so it can run anywhere
  const optionalDom = /typeof\s+DOMParser\s*[!=]==?\s*['"]undefined['"]/.test(withStrings)
  const found = new Set<UtilityEnv>()
  for (const [env, re] of API_PATTERNS) if (re.test(code)) found.add(env)
  for (const [env, re] of IMPORT_PATTERNS) if (re.test(withStrings)) found.add(env)
  if (optionalDom) found.delete('dom')
  return [...found].sort()
}

function writeIfChanged(file: string, content: string): boolean {
  if (existsSync(file) && readFileSync(file, 'utf8') === content) return false
  writeFileSync(file, content)
  return true
}

const ident = (i: number) => `u${i}`

/** Build every generated file's content in memory (no writes). */
export async function build(): Promise<{ count: number; files: Record<string, string> }> {
  const found = discover()
  const metas: UtilityMeta[] = []
  const examples: Record<string, UtilityExample[]> = {}
  const problems: string[] = []
  const seen = new Set<string>()

  for (const d of found) {
    const rel = '/' + path.relative(ROOT, d.file).split(path.sep).join('/')
    const mod = (await import(/* @vite-ignore */ rel)) as { default?: Utility }
    const util = mod.default
    if (!util || typeof util.apply !== 'function') { problems.push(`${d.dir}: no utility default export`); continue }
    if (util.id !== d.dir) problems.push(`${d.dir}: exports id "${util.id}" (must match its directory)`)
    if (seen.has(util.id)) problems.push(`${util.id}: duplicate id`)
    seen.add(util.id)
    metas.push(metaOf(util, detectEnv(d.source)))
    if (util.examples?.length) examples[util.id] = util.examples
  }
  if (problems.length) throw new Error('utility manifest problems:\n  ' + problems.join('\n  '))

  const ext = (d: Discovered) => (d.file.endsWith('.tsx') ? 'index.tsx' : 'index')
  const files: Record<string, string> = {
    'manifest.ts':
      HEADER +
      "import type { UtilityMeta } from '../../core/registry'\n\n" +
      `export const MANIFEST: UtilityMeta[] = ${JSON.stringify(metas, null, 2)}\n`,
    'examples.ts':
      HEADER +
      "import type { UtilityExample } from '../../types/utility'\n\n" +
      `export const EXAMPLES: Record<string, UtilityExample[]> = ${JSON.stringify(examples, null, 2)}\n`,
    'loaders.ts':
      HEADER +
      "import type { Utility } from '../../types/utility'\n\n" +
      'export const LOADERS: Record<string, () => Promise<{ default: Utility }>> = {\n' +
      found.map(d => `  ${JSON.stringify(d.dir)}: () => import('../${d.dir}/${ext(d)}'),`).join('\n') +
      '\n}\n',
    'static.ts':
      HEADER +
      "import type { Utility } from '../../types/utility'\n" +
      found.map((d, i) => `import ${ident(i)} from '../${d.dir}/${ext(d)}'`).join('\n') +
      '\n\nexport const STATIC_UTILITIES: Utility[] = [\n' +
      found.map((_, i) => `  ${ident(i)},`).join('\n') +
      '\n]\n',
  }
  return { count: metas.length, files }
}

/** Write the generated files, touching only those whose content changed. */
export async function generate(): Promise<{ count: number; written: string[] }> {
  const { count, files } = await build()
  mkdirSync(OUT_DIR, { recursive: true })
  const written: string[] = []
  for (const [name, content] of Object.entries(files)) {
    if (writeIfChanged(path.join(OUT_DIR, name), content)) written.push(name)
  }
  return { count, written }
}

export const GENERATED_DIR = OUT_DIR
