/**
 * Generates the preset index and loaders from `src/presets/<slug>/preset.ts`
 * (run by `npm run gen`, after the utility manifest it reads).
 *
 * Outputs (src/presets/_generated/, committed; `npm test` fails if stale):
 *   index.ts    — `PresetMeta` for every preset: names, chains, utility ids (no steps or samples)
 *   loaders.ts  — `slug → () => import(...)`: one lazy chunk per preset, its guide included (browser)
 *   static.ts   — static imports of every preset (Node: the SEO build, tests, scripts)
 *
 * Run with vite-node so TypeScript and the `@/` alias resolve exactly as in the app.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { MANIFEST } from '../src/utilities/_generated/manifest'
import { isBranchStep, isEachStep, isMacroStep, isUtilityStep, utilityIds } from '../src/core/steps'
import { itemNoun } from '../src/core/split'
import { displayName } from '../src/app/pages/seo'
import { toPipelineSteps, type Preset, type PresetMeta } from '../src/presets/types'

const ROOT = process.cwd()
const PRESET_DIR = path.join(ROOT, 'src', 'presets')
const OUT_DIR = path.join(PRESET_DIR, '_generated')
const HEADER = '// AUTO-GENERATED by scripts/gen-presets.ts — do not edit. Run `npm run gen`.\n'

/** Preset folders: every directory with a `preset.ts` (`_generated` and dot-folders aside). */
export function discoverPresets(): string[] {
  return readdirSync(PRESET_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory() && !d.name.startsWith('_') && !d.name.startsWith('.'))
    .map(d => d.name)
    .filter(dir => existsSync(path.join(PRESET_DIR, dir, 'preset.ts')))
    .sort()
}

/** Loads `src/presets/<dir>/preset.ts` (shared with `check-presets`). */
export async function loadPreset(dir: string): Promise<Preset | undefined> {
  const mod = (await import(/* @vite-ignore */ `/src/presets/${dir}/preset.ts`)) as { default?: Preset }
  return mod.default
}

/** `src/presets/<dir>/guide.md`, or null. */
export function readPresetGuide(dir: string): string | null {
  const file = path.join(PRESET_DIR, dir, 'guide.md')
  return existsSync(file) ? readFileSync(file, 'utf8') : null
}

const names = new Map(MANIFEST.map(m => [m.id, displayName(m.name)]))

export function metaOfPreset(preset: Preset): PresetMeta {
  const steps = toPipelineSteps(preset.steps)
  return {
    slug: preset.slug,
    name: preset.name,
    summary: preset.summary,
    category: preset.category,
    utilityIds: utilityIds(steps).sort(),
    // a step's own label first: it says what this use of the utility is for
    chain: steps.map(s => s.label ? s.label
      : isUtilityStep(s) ? names.get(s.utilityId) ?? s.utilityId
        : isBranchStep(s) ? `branch (${s.branches.length} lanes)`
          : isMacroStep(s) ? s.name
            : isEachStep(s) ? `run on each ${itemNoun(s.split.mode, 1)}` : 'step'),
    stepCount: steps.length,
    published: preset.published,
    ...(preset.updated ? { updated: preset.updated } : {}),
  }
}

const ident = (i: number) => `r${i}`

/** Build every generated file's content in memory (no writes). */
export async function build(): Promise<{ count: number; files: Record<string, string> }> {
  const dirs = discoverPresets()
  const metas: PresetMeta[] = []
  const problems: string[] = []
  const known = new Set(MANIFEST.map(m => m.id))
  for (const dir of dirs) {
    const preset = await loadPreset(dir)
    if (!preset || !Array.isArray(preset.steps)) { problems.push(`${dir}: no preset default export`); continue }
    if (preset.slug !== dir) problems.push(`${dir}: slug "${preset.slug}" must match its directory`)
    if (!existsSync(path.join(PRESET_DIR, dir, 'guide.md'))) problems.push(`${dir}: missing guide.md`)
    const meta = metaOfPreset(preset)
    const unknown = meta.utilityIds.filter(id => !known.has(id))
    if (unknown.length) problems.push(`${dir}: unknown utilities ${unknown.join(', ')}`)
    metas.push(meta)
  }
  if (problems.length) throw new Error('preset index problems:\n  ' + problems.join('\n  '))

  const files: Record<string, string> = {
    'index.ts':
      HEADER +
      "import type { PresetMeta } from '../types'\n\n" +
      `export const PRESET_INDEX: PresetMeta[] = ${JSON.stringify(metas, null, 2)}\n`,
    'loaders.ts':
      HEADER +
      "import type { Preset } from '../types'\n\n" +
      '/** One chunk per preset: its definition and its guide markdown. */\n' +
      'export const PRESET_LOADERS: Record<string, () => Promise<{ preset: Preset; guide: string }>> = {\n' +
      dirs.map(dir => `  ${JSON.stringify(dir)}: () => Promise.all([import('../${dir}/preset'), import('../${dir}/guide.md?raw')])` +
        '.then(([r, g]) => ({ preset: r.default, guide: g.default })),').join('\n') +
      '\n}\n',
    'static.ts':
      HEADER +
      "import type { Preset } from '../types'\n" +
      dirs.map((dir, i) => `import ${ident(i)} from '../${dir}/preset'`).join('\n') +
      '\n\nexport const STATIC_PRESETS: Preset[] = [\n' +
      dirs.map((_, i) => `  ${ident(i)},`).join('\n') +
      '\n]\n',
  }
  return { count: metas.length, files }
}

function writeIfChanged(file: string, content: string): boolean {
  if (existsSync(file) && readFileSync(file, 'utf8') === content) return false
  writeFileSync(file, content)
  return true
}

/** Write the generated files, touching only those whose content changed. */
export async function generate(): Promise<{ count: number; written: string[] }> {
  const { count, files } = await build()
  mkdirSync(OUT_DIR, { recursive: true })
  const written: string[] = []
  for (const [name, content] of Object.entries(files)) {
    if (writeIfChanged(path.join(OUT_DIR, name), content)) written.push(name)
  }
  return { count, written }
}

export const PRESETS_GENERATED_DIR = OUT_DIR
export { PRESET_DIR }
