/**
 * Emits `dist/sw.js`, a dependency-free service worker, at build time only
 * (`apply: 'build'` — never during `vite dev` or vitest's serve-mode config).
 *
 * The precache list is built from the real Rollup bundle: it walks static
 * imports starting at each entry chunk (never `dynamicImports`, which is how
 * the ~250 lazily-loaded utility chunks are excluded) and collects the CSS and
 * URL-referenced files (the module worker) each of those chunks pulls in.
 * `public/` files (manifest, icons) are copied verbatim by Vite under their
 * literal names, so they're passed in as `extra` rather than discovered from the bundle.
 */
import type { Plugin } from 'vite'
import type { OutputBundle, OutputChunk } from 'rollup'
import { createHash } from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'

export interface ChunkInfo {
  fileName: string
  isEntry: boolean
  /** Statically-imported chunk fileNames (Rollup's `imports`, not `dynamicImports`). */
  imports: string[]
  /** CSS asset fileNames this chunk pulls in. */
  css: string[]
  /** Other files this chunk loads by URL (e.g. `new Worker(new URL(...))`); precached but not walked. */
  assets?: string[]
}

/** The offline app shell: navigations fall back to this when the network is gone. */
export const APP_SHELL = '/index.html'

const STATIC_EXTRAS = [
  APP_SHELL,
  '/manifest.webmanifest',
  '/icons/icon-192.png',
  '/icons/icon-512.png',
  '/icons/icon-maskable-512.png',
  '/icons/apple-touch-icon.png',
]

/** Pure: the set of URLs that must be cached before the app can run offline. */
export function buildPrecacheList(chunks: ChunkInfo[], extra: string[] = STATIC_EXTRAS): string[] {
  const byFile = new Map(chunks.map((c) => [c.fileName, c]))
  const seen = new Set<string>()

  const walk = (fileName: string) => {
    if (seen.has(fileName)) return
    seen.add(fileName)
    const chunk = byFile.get(fileName)
    if (!chunk) return
    for (const css of chunk.css) seen.add(css)
    for (const asset of chunk.assets ?? []) seen.add(asset)
    for (const dep of chunk.imports) walk(dep)
  }
  for (const chunk of chunks) if (chunk.isEntry) walk(chunk.fileName)

  const urls = [...seen].map((f) => `/${f}`)
  return [...new Set([...extra, ...urls])]
}

/** Pure: a short, stable hash of a URL list, used as the cache-name version. */
export function hashAssetList(urls: string[]): string {
  const input = [...urls].sort().join('\n')
  let hash = 0x811c9dc5 // FNV-1a 32-bit
  for (let i = 0; i < input.length; i++) {
    hash ^= input.charCodeAt(i)
    hash = Math.imul(hash, 0x01000193)
  }
  return (hash >>> 0).toString(16).padStart(8, '0')
}

const isHashedAsset = (url: string) => url.startsWith('/assets/')

/**
 * Pure: the cache-version input for a precache list. `/assets/*` names already
 * carry a content hash; everything else (index.html, manifest, icons) keeps a
 * fixed name, so its content hash is folded in — otherwise an HTML- or
 * icon-only change would ship a byte-identical `sw.js` that browsers never
 * pick up, and the offline copy would stay stale forever.
 */
export function fingerprintPrecache(
  precache: string[],
  read: (url: string) => string | Uint8Array | undefined,
): string[] {
  return precache.map((url) => {
    if (isHashedAsset(url)) return url
    const content = read(url)
    if (content === undefined) throw new Error(`[pwa] precache entry ${url} is not in the build output`)
    return `${url}#${createHash('sha256').update(content).digest('hex').slice(0, 16)}`
  })
}

export const CACHE_PREFIX = 'subelt-precache-'

export interface ServiceWorkerOptions {
  /** Cache-name version; defaults to a hash of the precache list. */
  version?: string
  /** Every `/assets/*` URL this build ships; activate keeps runtime-cached copies of these. */
  assets?: string[]
}

/**
 * Pure: the full `sw.js` source for a given precache list. Routing:
 * cross-origin untouched; `/api/*` network-only; navigations network-first
 * falling back to the cached app shell offline; `/assets/*` and the other
 * precached files cache-first; `/blog/*` stale-while-revalidate. Activate
 * carries still-shipped `/assets/*` files over from, then deletes, every other
 * `subelt-precache-*` cache; `skipWaiting` fires only on a `SKIP_WAITING`
 * message; a `{type: 'CACHE_URLS', urls}` message caches `/assets/*` files the
 * page loaded before this worker controlled it.
 */
export function buildServiceWorkerSource(precache: string[], opts: ServiceWorkerOptions = {}): string {
  const cacheName = `${CACHE_PREFIX}${opts.version ?? hashAssetList(precache)}`
  return `// Generated by scripts/vite-plugin-pwa.ts — do not edit by hand.
const CACHE_PREFIX = ${JSON.stringify(CACHE_PREFIX)};
const CACHE_NAME = ${JSON.stringify(cacheName)};
const PRECACHE_URLS = ${JSON.stringify(precache)};
const BUILD_ASSETS = ${JSON.stringify(opts.assets ?? [])};
const APP_SHELL = ${JSON.stringify(APP_SHELL)};
const PRECACHED = new Set(PRECACHE_URLS);
const CURRENT_ASSETS = new Set(BUILD_ASSETS);
const MAX_WARM_URLS = 500;

function isHashedAsset(pathname) {
  return pathname.indexOf('/assets/') === 0;
}

// Only successful, non-HTML responses are stored: a cached 404 would be served
// forever, and the host answers a missing file with index.html (SPA fallback, 200).
// Nothing this worker caches at runtime is ever legitimately HTML.
function cacheable(response) {
  return response.ok && (response.headers.get('content-type') || '').indexOf('text/html') === -1;
}

// Browsers turn a redirected response used for a navigation into a network
// error, and hosts redirect /index.html -> / (Cloudflare 307s it), so the
// stored copy is rebuilt without the redirect flag.
function withoutRedirect(response) {
  if (!response.redirected) return Promise.resolve(response);
  return response.blob().then((body) => new Response(body, {
    status: response.status,
    statusText: response.statusText,
    headers: response.headers,
  }));
}

function precacheOne(cache, url) {
  // 'reload' skips the HTTP cache so a stale index.html can't outlive its assets;
  // content-hashed files are immutable, so the copy the page just loaded is reused
  const init = isHashedAsset(url) ? {} : { cache: 'reload' };
  return fetch(new Request(url, init)).then((response) => {
    if (!response.ok) throw new Error('precache ' + url + ' failed: ' + response.status);
    return withoutRedirect(response).then((clean) => cache.put(url, clean));
  });
}

function store(event, request, response) {
  if (!cacheable(response)) return;
  const copy = response.clone();
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.put(request, copy)).catch(() => {}));
}

function cacheFirst(event, request) {
  return caches.match(request).then((cached) => cached || fetch(request).then((response) => {
    store(event, request, response);
    return response;
  }));
}

function staleWhileRevalidate(event, request) {
  const network = fetch(request).then((response) => {
    store(event, request, response);
    return response;
  });
  event.waitUntil(network.catch(() => {}));
  return caches.match(request).then((cached) => cached || network);
}

function offlineShell() {
  return caches.open(CACHE_NAME)
    .then((cache) => cache.match(APP_SHELL))
    .then((cached) => cached || Response.error());
}

function warm(urls) {
  return caches.open(CACHE_NAME).then((cache) => Promise.all(urls.slice(0, MAX_WARM_URLS).map((raw) => {
    if (typeof raw !== 'string') return undefined;
    let url;
    try { url = new URL(raw, self.location.href); } catch (e) { return undefined; }
    if (url.origin !== self.location.origin || !isHashedAsset(url.pathname)) return undefined;
    return cache.match(url.href).then((hit) => hit || fetch(url.href).then((response) => {
      if (cacheable(response)) return cache.put(url.href, response);
    })).catch(() => {});
  })));
}

// Hashed files are immutable: the ones the previous version cached on use that
// this build still ships move across, so utilities used before an update keep
// working offline after it.
function carryOver(oldName) {
  return Promise.all([caches.open(oldName), caches.open(CACHE_NAME)]).then(([from, to]) =>
    from.keys().then((requests) => Promise.all(requests.map((request) => {
      if (!CURRENT_ASSETS.has(new URL(request.url).pathname)) return undefined;
      return to.match(request).then((have) => have || from.match(request).then((response) => {
        if (response) return to.put(request, response);
      }));
    }))));
}

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) =>
    Promise.all(PRECACHE_URLS.map((url) => precacheOne(cache, url)))));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((names) => Promise.all(
        names
          .filter((name) => name.indexOf(CACHE_PREFIX) === 0 && name !== CACHE_NAME)
          .map((name) => carryOver(name).catch(() => {}).then(() => caches.delete(name)))
      ))
      .then(() => { if (self.clients && self.clients.claim) return self.clients.claim(); })
  );
});

self.addEventListener('message', (event) => {
  // only this origin's own pages may drive the worker (defense in depth: browsers
  // already deliver only same-origin client messages)
  if (event.origin && event.origin !== self.location.origin) return;
  const data = event.data;
  if (data === 'SKIP_WAITING') {
    self.skipWaiting();
  } else if (data && data.type === 'CACHE_URLS' && Array.isArray(data.urls)) {
    event.waitUntil(warm(data.urls));
  }
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return; // cross-origin (analytics/ads/fonts): untouched

  if (url.pathname.indexOf('/api/') === 0) {
    event.respondWith(fetch(request)); // network-only
    return;
  }

  if (request.mode === 'navigate') {
    event.respondWith(fetch(request).catch(offlineShell));
    return;
  }

  if (isHashedAsset(url.pathname) || PRECACHED.has(url.pathname)) {
    event.respondWith(cacheFirst(event, request));
    return;
  }

  if (url.pathname.indexOf('/blog/') === 0) {
    event.respondWith(staleWhileRevalidate(event, request));
  }
});
`
}

function extractChunkInfo(bundle: OutputBundle): ChunkInfo[] {
  // Vite emits a module worker's own bundle as plain `.js` assets (no chunk
  // metadata); the chunk that spawns it holds its URL as a string literal.
  const scriptAssets = Object.values(bundle)
    .filter((file) => file.type === 'asset' && file.fileName.endsWith('.js'))
    .map((file) => file.fileName)
  const infos: ChunkInfo[] = []
  for (const file of Object.values(bundle)) {
    if (file.type !== 'chunk') continue
    const chunk = file as OutputChunk
    infos.push({
      fileName: chunk.fileName,
      isEntry: chunk.isEntry,
      imports: chunk.imports,
      css: [...(chunk.viteMetadata?.importedCss ?? [])],
      assets: [
        ...(chunk.viteMetadata?.importedAssets ?? []),
        ...scriptAssets.filter((name) => chunk.code.includes(path.posix.basename(name))),
      ],
    })
  }
  return infos
}

/**
 * Vite plugin: emits `sw.js` into the output directory. Client production
 * builds only. Runs `post` so Vite's HTML plugin has already emitted
 * `index.html` into the bundle (its content feeds the cache version); fails
 * the build if a precache entry is missing from the output.
 */
export function pwaServiceWorker(): Plugin {
  let publicDir = ''
  return {
    name: 'pwa-service-worker',
    apply: (_config, env) => env.command === 'build' && !env.isSsrBuild,
    enforce: 'post',
    configResolved(config) {
      publicDir = config.publicDir
    },
    generateBundle(_options, bundle) {
      const precache = buildPrecacheList(extractChunkInfo(bundle))
      const read = (url: string) => {
        const emitted = bundle[url.slice(1)]
        if (emitted) return emitted.type === 'asset' ? emitted.source : emitted.code
        const file = publicDir ? path.join(publicDir, url.slice(1)) : ''
        return file && fs.existsSync(file) ? fs.readFileSync(file) : undefined
      }
      let version: string
      try {
        version = hashAssetList(fingerprintPrecache(precache, read))
      } catch (e) {
        this.error((e as Error).message)
      }
      const assets = Object.keys(bundle).filter((name) => name.startsWith('assets/')).map((name) => `/${name}`)
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: buildServiceWorkerSource(precache, { version, assets }) })
    },
  }
}

// ---------------------------------------------------------------------------
// Build-output verification (used by the plugin's own test after a real build)
// ---------------------------------------------------------------------------

export interface BuildCheckResult {
  ok: boolean
  missing: string[]
  precache: string[]
}

/**
 * Reads a built `outDir`, parses `sw.js`'s precache and build-asset lists, and
 * confirms every entry exists on disk, along with the manifest and every icon it references.
 */
export function checkBuildOutput(outDir: string): BuildCheckResult {
  const exists = (url: string) => fs.existsSync(path.join(outDir, url.replace(/^\//, '')))
  const swSource = fs.readFileSync(path.join(outDir, 'sw.js'), 'utf8')
  const list = (name: string) => {
    const match = swSource.match(new RegExp(`const ${name} = (\\[[\\s\\S]*?\\]);`))
    if (!match) throw new Error(`sw.js: ${name} literal not found`)
    return JSON.parse(match[1]) as string[]
  }
  const precache = list('PRECACHE_URLS')

  const missing = new Set([...precache, ...list('BUILD_ASSETS')].filter((url) => !exists(url)))
  const required = ['/manifest.webmanifest', '/icons/icon-192.png', '/icons/icon-512.png', '/icons/icon-maskable-512.png']
  if (exists('/manifest.webmanifest')) {
    const manifest = JSON.parse(fs.readFileSync(path.join(outDir, 'manifest.webmanifest'), 'utf8'))
    for (const icon of manifest.icons ?? []) required.push(icon.src)
  }
  for (const url of required) if (!exists(url)) missing.add(url)

  return { ok: missing.size === 0, missing: [...missing], precache }
}
