// AUTO-GENERATED by scripts/gen-utilities.ts — do not edit. Run `npm run gen`.
import type { UtilityExample } from '../../types/utility'

export const EXAMPLES: Record<string, UtilityExample[]> = {
  "aes_decrypt": [
    {
      "title": "decrypt a blob produced by aes encrypt",
      "input": "+h7y7ZkH9CwYGGTiSlszGIehaPd912N5pRplQG5pSKozRrx5KFbu1piNEwBE1+7kl1RGdN3itmVFLQ==",
      "params": {
        "password": "hunter2",
        "iterations": 1000
      },
      "output": "secret message"
    }
  ],
  "aes_encrypt": [
    {
      "title": "encrypt with a password (output is random each run)",
      "input": "secret message",
      "params": {
        "password": "hunter2",
        "iterations": 1000
      },
      "outputMatches": "^[A-Za-z0-9+/]+=*$"
    }
  ],
  "align_columns": [
    {
      "title": "whitespace-delimited",
      "input": "name age\nAlice 30\nBob 7",
      "output": "name   age\nAlice  30\nBob    7"
    },
    {
      "title": "CSV, right-aligned",
      "input": "a,bb\nccc,d",
      "params": {
        "delimiter": ",",
        "align": "right"
      },
      "output": "  a  bb\nccc   d"
    }
  ],
  "alternating_case": [
    {
      "title": "default",
      "input": "hello world",
      "output": "hElLo WoRlD"
    }
  ],
  "argon2_hash": [
    {
      "title": "argon2id with a fixed salt (reproducible for the example)",
      "input": "hunter2",
      "params": {
        "iterations": 2,
        "memoryKiB": 8,
        "parallelism": 1,
        "salt": "0000000000000000"
      },
      "output": "$argon2id$v=19$m=8,t=2,p=1$AAAAAAAAAAA$kJIgd5fDoU8M8s/bTbAR8Pbft1SJMQmQGBZjeJT0PT4"
    }
  ],
  "ascii_banner": [
    {
      "title": "banner font",
      "input": "HI",
      "params": {
        "font": "banner",
        "spacing": 1
      },
      "output": "#   #  ###\n#   #   #\n#   #   #\n#####   #\n#   #   #\n#   #   #\n#   #  ###"
    }
  ],
  "atbash": [
    {
      "title": "a classic phrase",
      "input": "Attack at Dawn",
      "output": "Zggzxp zg Wzdm"
    }
  ],
  "base32_decode": [
    {
      "title": "rfc 4648",
      "input": "NBSWY3DP",
      "output": "hello"
    },
    {
      "title": "longer text",
      "input": "NBSWY3DPO5XXE3DE",
      "params": {
        "variant": "rfc4648"
      },
      "output": "helloworld"
    }
  ],
  "base32_encode": [
    {
      "title": "RFC 4648",
      "input": "hello",
      "output": "NBSWY3DP"
    },
    {
      "title": "z-base-32, no padding",
      "input": "hello",
      "params": {
        "variant": "z-base-32",
        "padding": false
      },
      "output": "pb1sa5dx"
    }
  ],
  "base58_decode": [
    {
      "title": "bitcoin alphabet",
      "input": "StV1DL6CwTryKyV",
      "output": "hello world"
    }
  ],
  "base58_encode": [
    {
      "title": "Bitcoin alphabet",
      "input": "hello world",
      "output": "StV1DL6CwTryKyV"
    },
    {
      "title": "leading zero bytes",
      "input": "00010203",
      "inputEncoding": "hex",
      "params": {
        "alphabet": "bitcoin"
      },
      "output": "1Ldp"
    }
  ],
  "base62_decode": [
    {
      "title": "standard alphabet",
      "input": "73XpUgyMwkGr29M",
      "output": "Hello World"
    }
  ],
  "base62_encode": [
    {
      "title": "standard alphabet",
      "input": "hello",
      "output": "7tQLFHz"
    },
    {
      "title": "inverted alphabet",
      "input": "hello",
      "params": {
        "alphabet": "inverted"
      },
      "output": "7TqlfhZ"
    }
  ],
  "base64_decode": [
    {
      "title": "decode to text",
      "input": "aGVsbG8gd29ybGQ=",
      "output": "hello world"
    }
  ],
  "base64_encode": [
    {
      "title": "plain text",
      "input": "hello world",
      "output": "aGVsbG8gd29ybGQ="
    },
    {
      "title": "raw bytes",
      "input": "48656c6c6f",
      "inputEncoding": "hex",
      "output": "SGVsbG8="
    }
  ],
  "base64url_decode": [
    {
      "title": "url-safe characters",
      "input": "aGVsbG8_d29ybGQ",
      "output": "hello?world"
    }
  ],
  "base64url_encode": [
    {
      "title": "URL-safe alphabet",
      "input": "hello world?",
      "output": "aGVsbG8gd29ybGQ_"
    },
    {
      "title": "with padding",
      "input": "hi",
      "params": {
        "padding": true
      },
      "output": "aGk="
    }
  ],
  "base85_decode": [
    {
      "title": "ascii85 with delimiters",
      "input": "<~87cURD_*#TDfTZ)~>",
      "output": "Hello, world"
    }
  ],
  "base85_encode": [
    {
      "title": "Ascii85",
      "input": "hello world",
      "output": "BOu!rD]j7BEbo7"
    },
    {
      "title": "Z85",
      "input": "hello world",
      "params": {
        "variant": "z85"
      },
      "output": "xK#0@zY<mxA+]m"
    }
  ],
  "base91_decode": [
    {
      "title": "decode text",
      "input": "\"ONK;WeMB2Q",
      "output": "Test 123!"
    }
  ],
  "base91_encode": [
    {
      "title": "plain text",
      "input": "hello world",
      "output": "TPwJh>Io2Tv!lE"
    }
  ],
  "bcrypt_hash": [
    {
      "title": "bcrypt with a fixed salt (reproducible for the example)",
      "input": "hunter2",
      "params": {
        "cost": 4,
        "salt": "000102030405060708090a0b0c0d0e0f"
      },
      "output": "$2a$04$..CA.uOD/eaGAOmJB.yMBurkTM.teJW4P/NXJXOT49X8IHvXALk4i"
    }
  ],
  "bcrypt_verify": [
    {
      "title": "a matching password",
      "input": "hunter2",
      "params": {
        "hash": "$2a$04$..CA.uOD/eaGAOmJB.yMBurkTM.teJW4P/NXJXOT49X8IHvXALk4i"
      },
      "output": "{\n  \"match\": true,\n  \"algorithm\": \"2a\",\n  \"cost\": 4,\n  \"salt\": \"..CA.uOD/eaGAOmJB.yMBu\",\n  \"reason\": \"\"\n}"
    }
  ],
  "binary_decode": [
    {
      "title": "8-bit groups",
      "input": "01101000 01101001",
      "output": "hi"
    }
  ],
  "binary_encode": [
    {
      "title": "one byte per group",
      "input": "Hi",
      "output": "01001000 01101001"
    },
    {
      "title": "no separator",
      "input": "Hi",
      "params": {
        "separator": "",
        "groupBytes": 0
      },
      "output": "0100100001101001"
    }
  ],
  "bit_ops": [
    {
      "title": "bitwise AND",
      "input": "1010",
      "params": {
        "operation": "and",
        "operand": "1100",
        "width": "8",
        "outputRadix": 2
      },
      "output": "01000000"
    },
    {
      "title": "shift left",
      "input": "5",
      "params": {
        "operation": "shift-left",
        "operand": "2",
        "width": "8",
        "inputRadix": 10,
        "outputRadix": 10
      },
      "output": "20"
    }
  ],
  "blake": [
    {
      "title": "BLAKE2b-256 of \"hello\"",
      "input": "hello",
      "output": "324dcf027dd4a30a932c441f365a25e86b173defa4b8e58948253471b81b72cf"
    },
    {
      "title": "BLAKE3-256, keyed",
      "input": "hello",
      "params": {
        "algorithm": "BLAKE3-256",
        "key": "abcdefghijklmnopqrstuvwxyz012345"
      },
      "output": "ebfd8681bea377568769ba0620b040a6809a6c4cc18bb64116498fb1b392ea75"
    }
  ],
  "bom": [
    {
      "title": "detect a UTF-8 mark",
      "input": "efbbbf68656c6c6f",
      "inputEncoding": "hex",
      "params": {
        "mode": "detect"
      },
      "output": "{\n  \"found\": true,\n  \"encoding\": \"utf-8\",\n  \"bytes\": \"EF BB BF\"\n}"
    },
    {
      "title": "add a UTF-8 mark",
      "input": "hello",
      "params": {
        "mode": "add",
        "encoding": "utf-8"
      },
      "output": "﻿hello"
    },
    {
      "title": "remove a mark",
      "input": "efbbbf68656c6c6f",
      "inputEncoding": "hex",
      "params": {
        "mode": "remove"
      },
      "output": "bytes[104, 101, 108, 108, 111]\nhex: [68, 65, 6c, 6c, 6f]\nutf8: hello"
    }
  ],
  "box_text": [
    {
      "title": "single-line border",
      "input": "Hi",
      "output": "┌────┐\n│ Hi │\n└────┘"
    },
    {
      "title": "double border with a title",
      "input": "Hello",
      "params": {
        "style": "double",
        "title": "Note"
      },
      "output": "╔═ Note ═╗\n║ Hello  ║\n╚════════╝"
    }
  ],
  "brotli_decompress": [
    {
      "title": "decompress a brotli stream to text",
      "input": "1b1c00001ca9539f3b740d22f426a742e82a8dad06d1a784d56935bc01",
      "inputEncoding": "hex",
      "params": {
        "output": "text"
      },
      "output": "Hello, Brotli! Hello, Brotli!"
    }
  ],
  "bytes_humanize": [
    {
      "title": "to human (binary)",
      "input": "1536",
      "params": {
        "direction": "to-human",
        "unit": "binary"
      },
      "output": "1.50 KiB"
    },
    {
      "title": "to bytes",
      "input": "1.5 GiB",
      "params": {
        "direction": "to-bytes"
      },
      "output": "1610612736"
    }
  ],
  "caesar": [
    {
      "title": "shift 3",
      "input": "Attack at Dawn",
      "params": {
        "shift": 3
      },
      "output": "Dwwdfn dw Gdzq"
    },
    {
      "title": "rot47",
      "input": "Hello, World! 123",
      "params": {
        "shift": 47,
        "mode": "rot47"
      },
      "output": "w6==@[ (@C=5P `ab"
    }
  ],
  "case": [
    {
      "title": "upper",
      "input": "hello world",
      "params": {
        "mode": "upper"
      },
      "output": "HELLO WORLD"
    },
    {
      "title": "title",
      "input": "hello world",
      "params": {
        "mode": "title"
      },
      "output": "Hello World"
    }
  ],
  "char_frequency": [
    {
      "title": "top 3 letters",
      "input": "banana",
      "params": {
        "top": 3
      },
      "output": "a  3  50.00%\nn  2  33.33%\nb  1  16.67%"
    },
    {
      "title": "case-folded, as json",
      "input": "AaBb",
      "params": {
        "ignoreCase": true,
        "format": "json"
      },
      "output": "{\n  \"totalCharacters\": 4,\n  \"uniqueCharacters\": 2,\n  \"characters\": [\n    {\n      \"char\": \"a\",\n      \"codePoint\": \"U+0061\",\n      \"count\": 2,\n      \"percent\": 50\n    },\n    {\n      \"char\": \"b\",\n      \"codePoint\": \"U+0062\",\n      \"count\": 2,\n      \"percent\": 50\n    }\n  ]\n}"
    }
  ],
  "charset_decode": [
    {
      "title": "windows-1252 accented bytes",
      "input": "e9e8",
      "inputEncoding": "hex",
      "params": {
        "charset": "windows-1252"
      },
      "output": "éè"
    }
  ],
  "charset_encode": [
    {
      "title": "Latin-1",
      "input": "café",
      "params": {
        "charset": "iso-8859-1"
      },
      "output": "bytes[99, 97, 102, 233]\nhex: [63, 61, 66, e9]\nutf8: caf�"
    },
    {
      "title": "windows-1252",
      "input": "café€",
      "params": {
        "charset": "windows-1252"
      },
      "output": "bytes[99, 97, 102, 233, 128]\nhex: [63, 61, 66, e9, 80]\nutf8: caf�"
    }
  ],
  "checksum": [
    {
      "title": "CRC-32 of \"hello\"",
      "input": "hello",
      "output": "3610a686"
    },
    {
      "title": "same digest as a decimal",
      "input": "hello",
      "params": {
        "output": "decimal"
      },
      "output": "907060870"
    }
  ],
  "checksum_verify": [
    {
      "title": "matching SHA-256 digest",
      "input": "hello",
      "params": {
        "algorithm": "SHA-256",
        "expected": "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
      },
      "output": "{\n  \"algorithm\": \"SHA-256\",\n  \"actual\": \"2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824\",\n  \"expected\": \"2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824\",\n  \"match\": true\n}"
    },
    {
      "title": "mismatched digest",
      "input": "hello",
      "params": {
        "algorithm": "MD5",
        "expected": "deadbeef"
      },
      "output": "{\n  \"algorithm\": \"MD5\",\n  \"actual\": \"5d41402abc4b2a76b9719d911017c592\",\n  \"expected\": \"deadbeef\",\n  \"match\": false\n}"
    }
  ],
  "chunk": [
    {
      "title": "chunk characters",
      "input": "abcdefgh",
      "params": {
        "size": 3,
        "unit": "characters",
        "separator": "-"
      },
      "output": "abc-def-gh"
    }
  ],
  "cidr": [
    {
      "title": "network info",
      "input": "192.168.1.0/24",
      "params": {
        "mode": "info"
      },
      "output": "{\n  \"network\": \"192.168.1.0\",\n  \"broadcast\": \"192.168.1.255\",\n  \"firstHost\": \"192.168.1.1\",\n  \"lastHost\": \"192.168.1.254\",\n  \"netmask\": \"255.255.255.0\",\n  \"wildcard\": \"0.0.0.255\",\n  \"prefix\": 24,\n  \"totalHosts\": 256,\n  \"usableHosts\": 254,\n  \"isPrivate\": true,\n  \"version\": 4\n}"
    },
    {
      "title": "expand every address",
      "input": "10.0.0.0/30",
      "params": {
        "mode": "expand",
        "limit": 8
      },
      "output": "10.0.0.0\n10.0.0.1\n10.0.0.2\n10.0.0.3"
    },
    {
      "title": "is an address inside the block?",
      "input": "10.0.0.0/24",
      "params": {
        "mode": "contains",
        "address": "10.0.0.5"
      },
      "output": "{\n  \"cidr\": \"10.0.0.0/24\",\n  \"address\": \"10.0.0.5\",\n  \"contains\": true,\n  \"version\": 4\n}"
    }
  ],
  "code_string_escape": [
    {
      "title": "JavaScript, quoted",
      "input": "She said \"hi\"\nnew line",
      "params": {
        "language": "javascript",
        "wrap": true
      },
      "output": "\"She said \\\"hi\\\"\\nnew line\""
    },
    {
      "title": "Python, single-quoted",
      "input": "path\\to\\file",
      "params": {
        "language": "python",
        "quote": "single",
        "wrap": true
      },
      "output": "'path\\\\to\\\\file'"
    }
  ],
  "code_string_unescape": [
    {
      "title": "escape sequences",
      "input": "\"hello\\nworld\\t!\"",
      "output": "hello\nworld\t!"
    },
    {
      "title": "python single-quoted literal",
      "input": "'it\\\\'s'",
      "params": {
        "language": "python"
      },
      "output": "it\\'s"
    }
  ],
  "codepoints_decode": [
    {
      "title": "U+ notation",
      "input": "U+1F600 U+1F44D",
      "output": "😀👍"
    },
    {
      "title": "hex without prefix",
      "input": "0x48 0x69",
      "params": {
        "format": "hex"
      },
      "output": "Hi"
    }
  ],
  "codepoints_encode": [
    {
      "title": "U+ format",
      "input": "Hi!",
      "output": "U+0048 U+0069 U+0021"
    },
    {
      "title": "decimal, astral character",
      "input": "A😀",
      "params": {
        "format": "decimal",
        "separator": ","
      },
      "output": "65,128512"
    }
  ],
  "collapse_whitespace": [
    {
      "title": "collapse spaces and blank lines",
      "input": "hello    world  \n\n\n\nfoo",
      "output": "hello world\n\nfoo"
    }
  ],
  "color_contrast": [
    {
      "title": "a borderline pair (looks 4.5, is not)",
      "input": "",
      "params": {
        "foreground": "#0078d7",
        "background": "#ffffff"
      },
      "output": "{\n  \"foreground\": \"#0078d7\",\n  \"background\": \"#ffffff\",\n  \"foregroundInput\": \"#0078d7\",\n  \"backgroundInput\": \"#ffffff\",\n  \"composited\": false,\n  \"ratio\": 4.5,\n  \"foregroundLuminance\": 0.1834,\n  \"backgroundLuminance\": 1,\n  \"AA\": {\n    \"normalText\": false,\n    \"largeText\": true,\n    \"ui\": true\n  },\n  \"AAA\": {\n    \"normalText\": false,\n    \"largeText\": false,\n    \"ui\": true\n  },\n  \"thresholds\": {\n    \"AA\": {\n      \"normalText\": 4.5,\n      \"largeText\": 3,\n      \"ui\": 3\n    },\n    \"AAA\": {\n      \"normalText\": 7,\n      \"largeText\": 4.5,\n      \"ui\": 3\n    }\n  },\n  \"summary\": \"4.5:1 — passes AA for large text and UI only\"\n}"
    },
    {
      "title": "a pair that fails AA normal text",
      "input": "",
      "params": {
        "foreground": "#777777",
        "background": "#ffffff"
      },
      "output": "{\n  \"foreground\": \"#777777\",\n  \"background\": \"#ffffff\",\n  \"foregroundInput\": \"#777777\",\n  \"backgroundInput\": \"#ffffff\",\n  \"composited\": false,\n  \"ratio\": 4.48,\n  \"foregroundLuminance\": 0.1845,\n  \"backgroundLuminance\": 1,\n  \"AA\": {\n    \"normalText\": false,\n    \"largeText\": true,\n    \"ui\": true\n  },\n  \"AAA\": {\n    \"normalText\": false,\n    \"largeText\": false,\n    \"ui\": true\n  },\n  \"thresholds\": {\n    \"AA\": {\n      \"normalText\": 4.5,\n      \"largeText\": 3,\n      \"ui\": 3\n    },\n    \"AAA\": {\n      \"normalText\": 7,\n      \"largeText\": 4.5,\n      \"ui\": 3\n    }\n  },\n  \"summary\": \"4.48:1 — passes AA for large text and UI only\"\n}"
    }
  ],
  "color_convert": [
    {
      "title": "named color to hsl",
      "input": "red",
      "params": {
        "to": "hsl",
        "perLine": true,
        "precision": 2
      },
      "output": "hsl(0, 100%, 50%)"
    },
    {
      "title": "hex to every notation",
      "input": "#336699",
      "params": {
        "to": "all",
        "perLine": true,
        "precision": 2
      },
      "output": "{\n  \"input\": \"#336699\",\n  \"hex\": \"#336699\",\n  \"hexAlpha\": \"#336699ff\",\n  \"rgb\": \"rgb(51, 102, 153)\",\n  \"rgba\": \"rgba(51, 102, 153, 1)\",\n  \"hsl\": \"hsl(210, 50%, 40%)\",\n  \"hsla\": \"hsla(210, 50%, 40%, 1)\",\n  \"hwb\": \"hwb(210 20% 40%)\",\n  \"lab\": \"lab(41.52 -4.57 -33.49)\",\n  \"lch\": \"lch(41.52 33.8 262.23)\",\n  \"oklab\": \"oklab(0.5 -0.03 -0.09)\",\n  \"oklch\": \"oklch(0.5 0.1 250.43)\",\n  \"named\": \"steelblue\",\n  \"namedExact\": false,\n  \"alpha\": 1,\n  \"components\": {\n    \"r\": 51,\n    \"g\": 102,\n    \"b\": 153\n  }\n}"
    }
  ],
  "columnar_decode": [
    {
      "title": "round trip with key ZEBRA",
      "input": "EODAEASRENEIELORCEECWDVFT",
      "params": {
        "key": "ZEBRA",
        "padChar": "X"
      },
      "output": "WEAREDISCOVEREDFLEEATONCE"
    }
  ],
  "columnar_encode": [
    {
      "title": "encode with key ZEBRA",
      "input": "WEAREDISCOVEREDFLEEATONCE",
      "params": {
        "key": "ZEBRA",
        "padChar": "X"
      },
      "output": "EODAEASRENEIELORCEECWDVFT"
    }
  ],
  "count": [
    {
      "title": "a couple of lines",
      "input": "Hello world\nfoo bar baz",
      "output": "characters: 23\nwords: 5\nlines: 2"
    }
  ],
  "cron_describe": [
    {
      "title": "weekday schedule",
      "input": "0 9 * * MON-FRI",
      "output": "At 09:00, Monday through Friday\n\nminute        0        minute 0\nhour          9        hour 9\nday of month  *        every day of the month\nmonth         *        every month\nday of week   MON-FRI  Monday through Friday"
    },
    {
      "title": "json output",
      "input": "*/15 * * * *",
      "params": {
        "format": "json"
      },
      "output": "{\n  \"expression\": \"*/15 * * * *\",\n  \"description\": \"Every 15 minutes\",\n  \"fields\": [\n    {\n      \"field\": \"minute\",\n      \"value\": \"*/15\",\n      \"description\": \"every 15 minutes\"\n    },\n    {\n      \"field\": \"hour\",\n      \"value\": \"*\",\n      \"description\": \"every hour\"\n    },\n    {\n      \"field\": \"day of month\",\n      \"value\": \"*\",\n      \"description\": \"every day of the month\"\n    },\n    {\n      \"field\": \"month\",\n      \"value\": \"*\",\n      \"description\": \"every month\"\n    },\n    {\n      \"field\": \"day of week\",\n      \"value\": \"*\",\n      \"description\": \"every day of the week\"\n    }\n  ]\n}"
    }
  ],
  "csv_columns": [
    {
      "title": "keep two columns by name",
      "input": "name,email,age\nAda Lovelace,ada@example.com,36\nGrace Hopper,grace@example.com,85",
      "params": {
        "columns": "name, age",
        "mode": "keep",
        "delimiter": "auto",
        "header": true
      },
      "output": "name,age\nAda Lovelace,36\nGrace Hopper,85"
    }
  ],
  "csv_delimiter": [
    {
      "title": "comma to semicolon",
      "input": "name,email,age\nAda Lovelace,ada@example.com,36\nGrace Hopper,grace@example.com,85",
      "params": {
        "from": "auto",
        "to": ";",
        "quoteAll": false
      },
      "output": "name;email;age\nAda Lovelace;ada@example.com;36\nGrace Hopper;grace@example.com;85"
    }
  ],
  "csv_normalize_headers": [
    {
      "title": "title case headers to snake_case",
      "input": "First Name,Last Name\nAda,Lovelace",
      "params": {
        "style": "snake",
        "delimiter": "auto",
        "dedupe": true
      },
      "output": "first_name,last_name\nAda,Lovelace"
    }
  ],
  "csv_to_html": [
    {
      "title": "CSV to an HTML table",
      "input": "name,email,age\nAda Lovelace,ada@example.com,36\nGrace Hopper,grace@example.com,85",
      "params": {
        "delimiter": "auto",
        "header": true,
        "className": "",
        "indent": 2
      },
      "output": "<table>\n  <thead>\n    <tr>\n      <th>name</th>\n      <th>email</th>\n      <th>age</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>Ada Lovelace</td>\n      <td>ada@example.com</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <td>Grace Hopper</td>\n      <td>grace@example.com</td>\n      <td>85</td>\n    </tr>\n  </tbody>\n</table>"
    }
  ],
  "csv_to_json": [
    {
      "title": "typed CSV to JSON records",
      "input": "name,email,age\nAda Lovelace,ada@example.com,36\nGrace Hopper,grace@example.com,85",
      "params": {
        "delimiter": "auto",
        "header": true,
        "typed": true,
        "trim": true,
        "indent": 2
      },
      "output": "[\n  {\n    \"name\": \"Ada Lovelace\",\n    \"email\": \"ada@example.com\",\n    \"age\": 36\n  },\n  {\n    \"name\": \"Grace Hopper\",\n    \"email\": \"grace@example.com\",\n    \"age\": 85\n  }\n]"
    }
  ],
  "csv_to_markdown": [
    {
      "title": "CSV to a left-aligned markdown table",
      "input": "name,email,age\nAda Lovelace,ada@example.com,36\nGrace Hopper,grace@example.com,85",
      "params": {
        "delimiter": "auto",
        "align": "left",
        "header": true
      },
      "output": "| name         | email             | age |\n| :----------- | :---------------- | :-- |\n| Ada Lovelace | ada@example.com   | 36  |\n| Grace Hopper | grace@example.com | 85  |"
    }
  ],
  "csv_to_sql": [
    {
      "title": "CSV to postgres INSERT statements",
      "input": "name,email,age\nAda Lovelace,ada@example.com,36\nGrace Hopper,grace@example.com,85",
      "params": {
        "table": "users",
        "delimiter": "auto",
        "dialect": "postgres",
        "batch": false,
        "nullToken": "",
        "createTable": false
      },
      "output": "INSERT INTO \"users\" (\"name\", \"email\", \"age\") VALUES ('Ada Lovelace', 'ada@example.com', 36);\nINSERT INTO \"users\" (\"name\", \"email\", \"age\") VALUES ('Grace Hopper', 'grace@example.com', 85);"
    }
  ],
  "csv_transpose": [
    {
      "title": "transpose a small grid",
      "input": "a,b,c\n1,2,3",
      "params": {
        "delimiter": "auto"
      },
      "output": "a,1\nb,2\nc,3"
    }
  ],
  "curl_build": [
    {
      "title": "POST with a JSON body",
      "input": "{\"method\":\"POST\",\"url\":\"https://api.example.com/users\",\"headers\":{\"Content-Type\":\"application/json\"},\"body\":\"{\\\"name\\\":\\\"Ada\\\"}\"}",
      "params": {
        "multiline": true,
        "flavor": "posix",
        "pretty": true
      },
      "output": "curl -X POST 'https://api.example.com/users' \\\n  -H 'Content-Type: application/json' \\\n  --data-raw '{\n  \"name\": \"Ada\"\n}'"
    }
  ],
  "curl_parse": [
    {
      "title": "POST with a JSON body",
      "input": "curl -X POST https://api.example.com/users -H \"Content-Type: application/json\" -d '{\"name\":\"Ada\"}'",
      "output": "{\n  \"method\": \"POST\",\n  \"url\": \"https://api.example.com/users\",\n  \"headers\": {\n    \"Content-Type\": \"application/json\"\n  },\n  \"body\": \"{\\\"name\\\":\\\"Ada\\\"}\",\n  \"auth\": null,\n  \"flags\": {\n    \"compressed\": false,\n    \"insecure\": false,\n    \"location\": false,\n    \"get\": false\n  }\n}"
    }
  ],
  "data_uri_build": [
    {
      "title": "base64",
      "input": "hello",
      "params": {
        "mime": "text/plain",
        "base64": true
      },
      "output": "data:text/plain;charset=utf-8;base64,aGVsbG8="
    },
    {
      "title": "percent-encoded",
      "input": "a b",
      "params": {
        "mime": "text/plain",
        "base64": false
      },
      "output": "data:text/plain;charset=utf-8,a%20b"
    }
  ],
  "data_uri_parse": [
    {
      "title": "text data URI",
      "input": "data:text/plain;charset=utf-8,Hello%20World",
      "output": "{\n  \"mime\": \"text/plain\",\n  \"charset\": \"utf-8\",\n  \"base64\": false,\n  \"data\": \"Hello World\",\n  \"size\": 11\n}"
    },
    {
      "title": "base64 payload as text",
      "input": "data:text/plain;base64,SGVsbG8=",
      "params": {
        "output": "text"
      },
      "output": "Hello"
    }
  ],
  "date_format": [
    {
      "title": "token format",
      "input": "2024-03-15T09:30:00Z",
      "params": {
        "format": "YYYY-MM-DD HH:mm:ss"
      },
      "output": "2024-03-15 09:30:00"
    },
    {
      "title": "strftime format",
      "input": "2024-03-15T09:30:00Z",
      "params": {
        "format": "%A, %B %d, %Y",
        "locale": "en-US"
      },
      "output": "Friday, March 15, 2024"
    }
  ],
  "deflate_compress": [
    {
      "title": "zlib-wrapped compression",
      "input": "Hello, DEFLATE!",
      "params": {
        "format": "zlib",
        "level": 6
      },
      "outputMatches": "^bytes\\[120, 156, 243, 72, 205, 201, 201, 215, 81, 112, 113, 117, 243, 113, 12, 113, 85, 04, 00, 37, 196, 04, 87\\]\\nhex: \\[78, 9c, f3, 48, cd, c9, c9, d7, 51, 70, 71, 75, f3, 71, 0c, 71, 55, 04, 00, 25, c4, 04, 57\\]"
    }
  ],
  "deflate_decompress": [
    {
      "title": "auto-detected zlib stream to text",
      "input": "789cf348cdc9c9d751707175f3710c7155040025c40457",
      "inputEncoding": "hex",
      "params": {
        "format": "auto",
        "output": "text"
      },
      "output": "Hello, DEFLATE!"
    }
  ],
  "detect_format": [
    {
      "title": "a small JSON object",
      "input": "{\"a\":1,\"b\":[2,3]}",
      "output": "[\n  {\n    \"format\": \"JSON\",\n    \"confidence\": 0.99,\n    \"note\": \"valid JSON object, 2 keys\"\n  },\n  {\n    \"format\": \"JSON5\",\n    \"confidence\": 0.45,\n    \"note\": \"valid JSON, which is a subset of JSON5\"\n  },\n  {\n    \"format\": \"YAML\",\n    \"confidence\": 0.3,\n    \"note\": \"JSON is also valid YAML\"\n  }\n]"
    }
  ],
  "diacritics": [
    {
      "title": "accented characters",
      "input": "café déjà vu",
      "output": "cafe deja vu"
    },
    {
      "title": "mixed diacritics",
      "input": "naïve Zürich",
      "output": "naive Zurich"
    }
  ],
  "duration_humanize": [
    {
      "title": "seconds to human",
      "input": "5400",
      "output": "1 hour 30 minutes"
    },
    {
      "title": "colon form back to seconds",
      "input": "1:30:00",
      "params": {
        "direction": "to-seconds"
      },
      "output": "5400"
    }
  ],
  "entropy": [
    {
      "title": "a short password",
      "input": "password123",
      "output": "{\n  \"unit\": \"bits\",\n  \"length\": 11,\n  \"uniqueCharacters\": 10,\n  \"entropyPerCharacter\": 3.28,\n  \"totalEntropy\": 36.05,\n  \"charsetSize\": 36,\n  \"charsetClasses\": [\n    \"lowercase\",\n    \"digits\"\n  ],\n  \"passwordEntropy\": 56.87,\n  \"passwordEntropyBits\": 56.87,\n  \"strength\": \"reasonable\",\n  \"guessesLog10\": 17.12,\n  \"crackTime\": \"3 months\"\n}"
    },
    {
      "title": "as a text report",
      "input": "correct horse battery staple",
      "params": {
        "format": "text"
      },
      "output": "entropy:                3.49 bits/char\ntotal entropy:          97.85 bits\nlength:                 28 characters\nunique characters:      13\ncharset size:           27 (lowercase, space)\npassword entropy:       133.14 bits\nstrength:               very strong\nest. crack time:        1.9e+22 years"
    }
  ],
  "env_to_json": [
    {
      "title": "comments, export prefix, quoted value",
      "input": "PORT=3000\nDEBUG=true\n# comment\nexport NAME=\"Ada Lovelace\"",
      "output": "{\n  \"PORT\": \"3000\",\n  \"DEBUG\": \"true\",\n  \"NAME\": \"Ada Lovelace\"\n}"
    },
    {
      "title": "${VAR} expansion",
      "input": "HOST=localhost\nURL=http://${HOST}:8080/api",
      "params": {
        "expand": true
      },
      "output": "{\n  \"HOST\": \"localhost\",\n  \"URL\": \"http://localhost:8080/api\"\n}"
    },
    {
      "title": "typed values",
      "input": "COUNT=42\nENABLED=true",
      "params": {
        "typed": true
      },
      "output": "{\n  \"COUNT\": 42,\n  \"ENABLED\": true\n}"
    }
  ],
  "escape_html": [
    {
      "title": "special characters",
      "input": "Tom & Jerry <3> \"quotes\" 'single'",
      "output": "Tom &amp; Jerry &lt;3&gt; &quot;quotes&quot; &#39;single&#39;"
    }
  ],
  "extract_preset": [
    {
      "title": "urls",
      "input": "Visit https://example.com and http://test.org today",
      "params": {
        "type": "urls"
      },
      "output": "https://example.com\nhttp://test.org"
    },
    {
      "title": "several types at once",
      "input": "Email ada@example.com or call 555-123-4567",
      "params": {
        "type": [
          "emails",
          "phone"
        ]
      },
      "output": "ada@example.com\n555-123-4567"
    }
  ],
  "fake_data": [
    {
      "title": "seeded names, one per line",
      "input": "",
      "params": {
        "type": "name",
        "count": 3,
        "seed": 42
      },
      "output": "Chloe Clark\nJulian Green\nMia Young"
    },
    {
      "title": "a row of fake data as JSON",
      "input": "",
      "params": {
        "type": "row",
        "count": 1,
        "format": "json",
        "seed": 7
      },
      "output": "[\n  {\n    \"id\": 1,\n    \"firstName\": \"Olivia\",\n    \"lastName\": \"Brown\",\n    \"email\": \"olivia.brown@fincordfinance.example\",\n    \"username\": \"obrown521\",\n    \"phone\": \"+1 (310) 555-0146\",\n    \"address\": \"2400 Jefferson Way, Bristol, DE 76607\",\n    \"city\": \"Oakland\",\n    \"country\": \"Germany\",\n    \"company\": \"Fourth Coffee\",\n    \"jobTitle\": \"HR Coordinator\",\n    \"url\": \"https://tailspintoys.example/ad-aperiam\",\n    \"ipv4\": \"196.48.36.40\",\n    \"date\": \"2009-07-24\",\n    \"price\": \"$75.43\"\n  }\n]"
    }
  ],
  "filter_lines_by_length": [
    {
      "title": "by character length",
      "input": "a\nbb\nccc\ndddd",
      "params": {
        "min": 2,
        "max": 3,
        "unit": "characters"
      },
      "output": "bb\nccc"
    },
    {
      "title": "by word count",
      "input": "one two\nthree four five\nsix",
      "params": {
        "min": 2,
        "max": 0,
        "unit": "words"
      },
      "output": "one two\nthree four five"
    }
  ],
  "format_case": [
    {
      "title": "camelCase",
      "input": "hello world example",
      "params": {
        "mode": "camel"
      },
      "output": "helloWorldExample"
    },
    {
      "title": "snake_case",
      "input": "Hello World Example",
      "params": {
        "mode": "snake"
      },
      "output": "hello_world_example"
    }
  ],
  "get_bytes": [
    {
      "title": "utf8 mode",
      "input": "Hi",
      "params": {
        "mode": "utf8"
      },
      "output": "bytes[72, 105]\nhex: [48, 69]\nutf8: Hi"
    },
    {
      "title": "hex mode",
      "input": "48 69",
      "params": {
        "mode": "hex"
      },
      "output": "bytes[72, 105]\nhex: [48, 69]\nutf8: Hi"
    },
    {
      "title": "unicode mode (UTF-16 code units)",
      "input": "Hi",
      "params": {
        "mode": "unicode"
      },
      "output": "bytes[00, 72, 00, 105]\nhex: [00, 48, 00, 69]\nutf8: \u0000H\u0000i"
    }
  ],
  "grep_lines": [
    {
      "title": "substring match",
      "input": "apple\nbanana\ncherry\ndate",
      "params": {
        "pattern": "an"
      },
      "output": "banana"
    },
    {
      "title": "regex with line numbers",
      "input": "foo\nbar\nfoobar\nbaz",
      "params": {
        "pattern": "^foo",
        "regex": true,
        "lineNumbers": true
      },
      "output": "1:foo\n3:foobar"
    }
  ],
  "gzip_compress": [
    {
      "title": "compress to a gzip stream",
      "input": "Hello, gzip!",
      "params": {
        "level": 6
      },
      "outputMatches": "^bytes\\[31, 139, 08, 00, 00, 00, 00, 00, 00, 03, 243, 72, 205, 201, 201, 215, 81, 72, 175, 202, 44, 80, 04, 00, 62, 61, 15, 16, 12, 00, 00, 00\\]\\nhex: \\[1f, 8b, 08, 00, 00, 00, 00, 00, 00, 03, f3, 48, cd, c9, c9, d7, 51, 48, af, ca, 2c, 50, 04, 00, 3e, 3d, 0f, 10, 0c, 00, 00, 00\\]"
    }
  ],
  "gzip_decompress": [
    {
      "title": "decompress a gzip stream to text",
      "input": "1f8b0800000000000003f348cdc9c9d75148afca2c5004003e3d0f100c000000",
      "inputEncoding": "hex",
      "params": {
        "output": "text"
      },
      "output": "Hello, gzip!"
    }
  ],
  "hash": [
    {
      "title": "SHA-256",
      "input": "hello",
      "params": {
        "algo": "SHA-256"
      },
      "output": "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
    },
    {
      "title": "SHA-1",
      "input": "hello",
      "params": {
        "algo": "SHA-1"
      },
      "output": "aaf4c61ddcc5e8a2dabede0f3b482cd9aea9434d"
    }
  ],
  "head": [
    {
      "title": "first 2 lines",
      "input": "one\ntwo\nthree\nfour\nfive",
      "params": {
        "count": 2,
        "unit": "lines"
      },
      "output": "one\ntwo"
    },
    {
      "title": "first 5 characters",
      "input": "hello world",
      "params": {
        "count": 5,
        "unit": "characters"
      },
      "output": "hello"
    }
  ],
  "hex_decode": [
    {
      "title": "decode to bytes",
      "input": "68656c6c6f",
      "output": "bytes[104, 101, 108, 108, 111]\nhex: [68, 65, 6c, 6c, 6f]\nutf8: hello"
    }
  ],
  "hex_dump": [
    {
      "title": "a short string, 8 bytes per row",
      "input": "Hi!",
      "params": {
        "width": 8
      },
      "output": "00000000  48 69 21                 |Hi!|"
    }
  ],
  "hex_encode": [
    {
      "title": "text to hex",
      "input": "Hi",
      "output": "4869"
    }
  ],
  "hmac": [
    {
      "title": "text key, hex output",
      "input": "hello",
      "params": {
        "algorithm": "SHA-256",
        "key": "secret",
        "keyFormat": "text",
        "output": "hex"
      },
      "output": "88aab3ede8d3adf94d26ab90d3bafd4a2083070c3bcce9c014ee04a443847c0b"
    },
    {
      "title": "hex key, base64 output",
      "input": "hello",
      "params": {
        "algorithm": "SHA-256",
        "key": "deadbeef",
        "keyFormat": "hex",
        "output": "base64"
      },
      "output": "KXpxXaiiuT8of9Xm59R2S8Pomd91VtWIiaT5hmVsgAk="
    }
  ],
  "html_entity_decode": [
    {
      "title": "named + numeric entities",
      "input": "&lt;div&gt;Caf&eacute;&lt;/div&gt;",
      "output": "<div>Café</div>"
    }
  ],
  "html_entity_encode": [
    {
      "title": "named, non-ascii scope",
      "input": "café < 5 & \"ok\"",
      "output": "caf&eacute; &lt; 5 &amp; &quot;ok&quot;"
    },
    {
      "title": "decimal, every character",
      "input": "café",
      "params": {
        "mode": "decimal",
        "scope": "all"
      },
      "output": "&#99;&#97;&#102;&#233;"
    }
  ],
  "html_table_to_csv": [
    {
      "title": "simple table with header",
      "input": "<table><tr><th>Name</th><th>Age</th></tr><tr><td>Ada</td><td>36</td></tr><tr><td>Grace</td><td>85</td></tr></table>",
      "output": "Name,Age\nAda,36\nGrace,85"
    },
    {
      "title": "custom delimiter, quoted cell",
      "input": "<table><tr><td>a;b</td><td>c</td></tr></table>",
      "params": {
        "delimiter": ";"
      },
      "output": "\"a;b\";c"
    }
  ],
  "html_to_markdown": [
    {
      "title": "heading, bold, link",
      "input": "<h1>Title</h1><p>Some <strong>bold</strong> and <a href=\"https://example.com\">a link</a>.</p>",
      "output": "# Title\n\nSome **bold** and [a link](https://example.com)."
    },
    {
      "title": "custom bullet marker",
      "input": "<ul><li>one</li><li>two</li></ul>",
      "params": {
        "bulletMarker": "*"
      },
      "output": "*   one\n*   two"
    }
  ],
  "http_headers_build": [
    {
      "title": "request headers with a start line",
      "input": "{\"method\":\"GET\",\"path\":\"/users\",\"headers\":{\"content-type\":\"application/json\",\"x-request-id\":\"abc123\"}}",
      "params": {
        "canonicalCase": true,
        "eol": "lf"
      },
      "output": "GET /users HTTP/1.1\nContent-Type: application/json\nX-Request-Id: abc123"
    }
  ],
  "http_headers_parse": [
    {
      "title": "a request with a start line",
      "input": "GET /users HTTP/1.1\r\nHost: api.example.com\r\nAccept: application/json\r\n",
      "params": {
        "lowercaseNames": true,
        "indent": 2
      },
      "output": "{\n  \"startLine\": \"GET /users HTTP/1.1\",\n  \"method\": \"GET\",\n  \"path\": \"/users\",\n  \"httpVersion\": \"HTTP/1.1\",\n  \"headers\": {\n    \"host\": \"api.example.com\",\n    \"accept\": \"application/json\"\n  }\n}"
    }
  ],
  "ieee754": [
    {
      "title": "number to hex bits",
      "input": "1.5",
      "params": {
        "direction": "to-bits",
        "precision": "double",
        "format": "hex"
      },
      "output": "0x3ff8000000000000"
    },
    {
      "title": "hex bits to number",
      "input": "0x3ff8000000000000",
      "params": {
        "direction": "to-number",
        "precision": "double",
        "format": "hex"
      },
      "output": "1.5"
    }
  ],
  "indent": [
    {
      "title": "add two spaces",
      "input": "a\nb",
      "params": {
        "amount": 2,
        "character": "space"
      },
      "output": "  a\n  b"
    },
    {
      "title": "auto-dedent",
      "input": "    a\n    b",
      "params": {
        "mode": "auto-dedent"
      },
      "output": "a\nb"
    }
  ],
  "ini_to_json": [
    {
      "title": "globals and a section",
      "input": "app=belt\n\n[server]\nhost=localhost\nport=8080\ndebug=true",
      "output": "{\n  \"app\": \"belt\",\n  \"server\": {\n    \"host\": \"localhost\",\n    \"port\": \"8080\",\n    \"debug\": \"true\"\n  }\n}"
    },
    {
      "title": "typed values",
      "input": "app=belt\n\n[server]\nport=8080\nenabled=yes",
      "params": {
        "typed": true
      },
      "output": "{\n  \"app\": \"belt\",\n  \"server\": {\n    \"port\": 8080,\n    \"enabled\": true\n  }\n}"
    },
    {
      "title": "dotted section nesting",
      "input": "[db.primary]\nhost=localhost",
      "params": {
        "nested": true
      },
      "output": "{\n  \"db\": {\n    \"primary\": {\n      \"host\": \"localhost\"\n    }\n  }\n}"
    }
  ],
  "initials": [
    {
      "title": "skip small words",
      "input": "The Quick Brown Fox",
      "params": {
        "separator": "",
        "uppercase": true,
        "skipSmallWords": true,
        "maxLength": 0
      },
      "output": "TQBF"
    },
    {
      "title": "dotted acronym",
      "input": "Node.js Foundation",
      "params": {
        "separator": ".",
        "uppercase": true,
        "skipSmallWords": false,
        "maxLength": 0
      },
      "output": "N.J.F"
    }
  ],
  "insert_at": [
    {
      "title": "insert into the middle",
      "input": "Hello World",
      "params": {
        "text": ", dear",
        "position": 5,
        "mode": "insert",
        "perLine": false
      },
      "output": "Hello, dear World"
    },
    {
      "title": "overwrite per line, negative-from-end not used",
      "input": "aaaaa\nbbbbb",
      "params": {
        "text": "XX",
        "position": 2,
        "mode": "overwrite",
        "perLine": true
      },
      "output": "aaXXa\nbbXXb"
    }
  ],
  "ip_convert": [
    {
      "title": "address to integer",
      "input": "192.168.1.1",
      "params": {
        "mode": "to-integer"
      },
      "output": "3232235777"
    },
    {
      "title": "integer to address",
      "input": "3232235777",
      "params": {
        "mode": "to-address"
      },
      "output": "192.168.1.1"
    },
    {
      "title": "compress IPv6",
      "input": "2001:0db8:0000:0000:0000:0000:0000:0001",
      "params": {
        "mode": "ipv6-compress"
      },
      "output": "2001:db8::1"
    }
  ],
  "json_diff": [
    {
      "title": "a changed and an added key",
      "input": "{\"a\":1,\"b\":2}",
      "params": {
        "other": "{\"a\":1,\"b\":3,\"c\":4}",
        "format": "summary"
      },
      "output": "{\n  \"equal\": false,\n  \"counts\": {\n    \"added\": 1,\n    \"removed\": 0,\n    \"changed\": 1,\n    \"total\": 2\n  },\n  \"added\": [\n    {\n      \"path\": \"$.c\",\n      \"value\": 4\n    }\n  ],\n  \"removed\": [],\n  \"changed\": [\n    {\n      \"path\": \"$.b\",\n      \"from\": 2,\n      \"to\": 3\n    }\n  ]\n}"
    }
  ],
  "json_escape": [
    {
      "title": "newlines, tabs and quotes",
      "input": "Line1\nLine2\t\"quoted\"",
      "output": "Line1\\nLine2\\t\\\"quoted\\\""
    }
  ],
  "json_flatten": [
    {
      "title": "nested object and array",
      "input": "{\"user\":{\"name\":\"Ada\",\"tags\":[\"core\",\"dev\"]},\"active\":true}",
      "output": "{\n  \"user.name\": \"Ada\",\n  \"user.tags[0]\": \"core\",\n  \"user.tags[1]\": \"dev\",\n  \"active\": true\n}"
    },
    {
      "title": "dot notation for array indices",
      "input": "{\"user\":{\"tags\":[\"x\",\"y\"]}}",
      "params": {
        "arrayNotation": "dot",
        "indent": 0
      },
      "output": "{\"user.tags.0\":\"x\",\"user.tags.1\":\"y\"}"
    }
  ],
  "json_minify": [
    {
      "title": "strip formatting",
      "input": "{\n  \"a\": 1,\n  \"b\": [1, 2, 3]\n}",
      "output": "{\"a\":1,\"b\":[1,2,3]}"
    }
  ],
  "json_pretty": [
    {
      "title": "default 2-space indent",
      "input": "{\"a\":1,\"b\":[1,2,3]}",
      "output": "{\n  \"a\": 1,\n  \"b\": [\n    1,\n    2,\n    3\n  ]\n}"
    },
    {
      "title": "4-space indent",
      "input": "{\"a\":1}",
      "params": {
        "indent": 4
      },
      "output": "{\n    \"a\": 1\n}"
    }
  ],
  "json_schema_validate": [
    {
      "title": "document satisfies the schema",
      "input": "{\"id\":1,\"email\":\"ada@example.com\"}",
      "params": {
        "schema": "{\"type\":\"object\",\"required\":[\"id\",\"email\"],\"properties\":{\"id\":{\"type\":\"integer\"},\"email\":{\"type\":\"string\",\"format\":\"email\"}}}"
      },
      "output": "{\n  \"valid\": true,\n  \"errors\": []\n}"
    },
    {
      "title": "missing property and wrong type",
      "input": "{\"id\":\"x\"}",
      "params": {
        "schema": "{\"type\":\"object\",\"required\":[\"id\",\"email\"],\"properties\":{\"id\":{\"type\":\"integer\"}}}"
      },
      "output": "{\n  \"valid\": false,\n  \"errors\": [\n    {\n      \"path\": \"$\",\n      \"message\": \"missing required property \\\"email\\\"\"\n    },\n    {\n      \"path\": \"$.id\",\n      \"message\": \"expected type integer, got string\"\n    }\n  ]\n}"
    }
  ],
  "json_sort_keys": [
    {
      "title": "sorts every depth (the default)",
      "input": "{\"banana\":1,\"apple\":2,\"cherry\":{\"z\":1,\"a\":2}}",
      "output": "{\n  \"apple\": 2,\n  \"banana\": 1,\n  \"cherry\": {\n    \"a\": 2,\n    \"z\": 1\n  }\n}"
    },
    {
      "title": "descending order, compact",
      "input": "{\"banana\":1,\"apple\":2}",
      "params": {
        "direction": "desc",
        "indent": 0
      },
      "output": "{\"banana\":1,\"apple\":2}"
    }
  ],
  "json_to_csv": [
    {
      "title": "array of objects with header",
      "input": "[{\"name\":\"Ada\",\"age\":36},{\"name\":\"Grace\",\"age\":85}]",
      "output": "name,age\nAda,36\nGrace,85"
    },
    {
      "title": "tab delimiter (named)",
      "input": "[{\"a\":1,\"b\":2}]",
      "params": {
        "delimiter": "tab"
      },
      "output": "a\tb\n1\t2"
    }
  ],
  "json_to_env": [
    {
      "title": "flat and nested keys",
      "input": "{\"port\":3000,\"debug\":true,\"db\":{\"host\":\"localhost\"}}",
      "output": "PORT=3000\nDEBUG=true\nDB_HOST=localhost"
    },
    {
      "title": "always quote values",
      "input": "{\"greeting\":\"hi there\"}",
      "params": {
        "quote": "always"
      },
      "output": "GREETING=\"hi there\""
    }
  ],
  "json_to_ini": [
    {
      "title": "globals then a section",
      "input": "{\"app\":\"belt\",\"debug\":false,\"server\":{\"host\":\"localhost\",\"port\":8080}}",
      "inputEncoding": "json",
      "output": "app=belt\ndebug=false\n\n[server]\nhost=localhost\nport=8080"
    }
  ],
  "json_to_jsonl": [
    {
      "title": "array of records",
      "input": "[{\"id\":1,\"name\":\"Ada\"},{\"id\":2,\"name\":\"Grace\"}]",
      "output": "{\"id\":1,\"name\":\"Ada\"}\n{\"id\":2,\"name\":\"Grace\"}"
    }
  ],
  "json_to_query_string": [
    {
      "title": "object with an array field",
      "input": "{\"q\":\"hello world\",\"tags\":[\"a\",\"b\"]}",
      "params": {
        "arrayFormat": "repeat",
        "nested": "bracket",
        "encode": true
      },
      "output": "q=hello%20world&tags=a&tags=b"
    }
  ],
  "json_to_schema": [
    {
      "title": "infer a schema from a sample",
      "input": "{\"id\":1,\"name\":\"Ada\",\"tags\":[\"core\"],\"active\":true}",
      "output": "{\n  \"$schema\": \"http://json-schema.org/draft-07/schema#\",\n  \"title\": \"Root\",\n  \"type\": \"object\",\n  \"properties\": {\n    \"id\": {\n      \"type\": \"integer\"\n    },\n    \"name\": {\n      \"type\": \"string\"\n    },\n    \"tags\": {\n      \"type\": \"array\",\n      \"items\": {\n        \"type\": \"string\"\n      }\n    },\n    \"active\": {\n      \"type\": \"boolean\"\n    }\n  },\n  \"required\": [\n    \"id\",\n    \"name\",\n    \"tags\",\n    \"active\"\n  ]\n}"
    }
  ],
  "json_to_toml": [
    {
      "title": "scalars and an array",
      "input": "{\"title\":\"belt\",\"port\":8080,\"tags\":[\"cli\",\"text\"]}",
      "output": "title = \"belt\"\nport = 8080\ntags = [ \"cli\", \"text\" ]\n"
    },
    {
      "title": "nested object becomes a table",
      "input": "{\"owner\":{\"name\":\"Ann\",\"active\":true}}",
      "output": "[owner]\nname = \"Ann\"\nactive = true\n"
    }
  ],
  "json_to_typescript": [
    {
      "title": "infer an interface from a sample",
      "input": "{\"id\":1,\"name\":\"Ada\",\"tags\":[\"core\",\"dev\"],\"active\":true}",
      "output": "export interface Root {\n  id: number;\n  name: string;\n  tags: string[];\n  active: boolean;\n}"
    }
  ],
  "json_to_xml": [
    {
      "title": "single top-level key becomes the root, @attr prefix",
      "input": "{\"note\":{\"@id\":\"1\",\"to\":\"Tove\",\"from\":\"Jani\"}}",
      "output": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<note id=\"1\">\n  <to>Tove</to>\n  <from>Jani</from>\n</note>"
    },
    {
      "title": "no declaration",
      "input": "{\"config\":{\"debug\":true,\"retries\":3}}",
      "params": {
        "declaration": false
      },
      "output": "<config>\n  <debug>true</debug>\n  <retries>3</retries>\n</config>"
    }
  ],
  "json_to_yaml": [
    {
      "title": "object with a nested array",
      "input": "{\"name\":\"belt\",\"version\":\"1.2.0\",\"tags\":[\"cli\",\"text\"]}",
      "output": "name: belt\nversion: 1.2.0\ntags:\n  - cli\n  - text\n"
    }
  ],
  "json_unescape": [
    {
      "title": "newline and tab escapes",
      "input": "line1\\nline2\\ttabbed",
      "output": "line1\nline2\ttabbed"
    }
  ],
  "json_unflatten": [
    {
      "title": "rebuild nested object and array",
      "input": "{\"user.name\":\"ada\",\"user.tags[0]\":\"x\",\"user.tags[1]\":\"y\",\"ok\":true}",
      "output": "{\n  \"user\": {\n    \"name\": \"ada\",\n    \"tags\": [\n      \"x\",\n      \"y\"\n    ]\n  },\n  \"ok\": true\n}"
    }
  ],
  "json_validate": [
    {
      "title": "valid document",
      "input": "{\"id\":1,\"name\":\"Ada\"}",
      "output": "{\n  \"valid\": true,\n  \"error\": null,\n  \"line\": null,\n  \"column\": null,\n  \"excerpt\": null\n}"
    },
    {
      "title": "trailing comma rejected in strict mode",
      "input": "{\"id\":1,\"name\":\"Ada\",}",
      "output": "{\n  \"valid\": false,\n  \"error\": \"trailing comma is not allowed in strict JSON\",\n  \"line\": 1,\n  \"column\": 21,\n  \"excerpt\": \"{\\\"id\\\":1,\\\"name\\\":\\\"Ada\\\",}\"\n}"
    },
    {
      "title": "same trailing comma accepted when strict is off",
      "input": "{\"id\":1,}",
      "params": {
        "strict": false
      },
      "output": "{\n  \"valid\": true,\n  \"error\": null,\n  \"line\": null,\n  \"column\": null,\n  \"excerpt\": null\n}"
    }
  ],
  "json5_parse": [
    {
      "title": "comments, trailing comma, unquoted keys, single quotes",
      "input": "{\n  // a comment\n  id: 1,\n  name: 'Ada',\n  tags: [1, 2,],\n}",
      "output": "{\n  \"id\": 1,\n  \"name\": \"Ada\",\n  \"tags\": [\n    1,\n    2\n  ]\n}"
    }
  ],
  "jsonl_to_json": [
    {
      "title": "two records into an array",
      "input": "{\"id\":1,\"name\":\"Ada\"}\n{\"id\":2,\"name\":\"Grace\"}",
      "output": "[\n  {\n    \"id\": 1,\n    \"name\": \"Ada\"\n  },\n  {\n    \"id\": 2,\n    \"name\": \"Grace\"\n  }\n]"
    },
    {
      "title": "skip blank and invalid lines",
      "input": "{\"id\":1,\"name\":\"Ada\"}\n\nnot json\n{\"id\":2,\"name\":\"Grace\"}",
      "params": {
        "onError": "skip"
      },
      "output": "[\n  {\n    \"id\": 1,\n    \"name\": \"Ada\"\n  },\n  {\n    \"id\": 2,\n    \"name\": \"Grace\"\n  }\n]"
    }
  ],
  "jsonpath": [
    {
      "title": "filter expression on nested array",
      "input": "{\"store\":{\"book\":[{\"title\":\"A\",\"price\":8},{\"title\":\"B\",\"price\":22}]}}",
      "params": {
        "path": "$..book[?(@.price < 10)].title"
      },
      "output": "[\n  \"A\"\n]"
    },
    {
      "title": "count matches",
      "input": "{\"store\":{\"book\":[{\"title\":\"A\",\"price\":8},{\"title\":\"B\",\"price\":22}]}}",
      "params": {
        "path": "$.store.book[*].price",
        "mode": "count"
      },
      "output": "2"
    }
  ],
  "jwt_decode": [
    {
      "title": "full decode",
      "input": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
      "output": "{\n  \"header\": {\n    \"alg\": \"HS256\",\n    \"typ\": \"JWT\"\n  },\n  \"payload\": {\n    \"sub\": \"1234567890\",\n    \"name\": \"John Doe\",\n    \"iat\": 1516239022\n  },\n  \"signature\": \"SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c\",\n  \"expiresAt\": null,\n  \"issuedAt\": \"2018-01-18T01:30:22.000Z\",\n  \"notBefore\": null,\n  \"isExpired\": false\n}"
    }
  ],
  "jwt_verify": [
    {
      "title": "valid, unexpired token",
      "input": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiZXhwIjo0MTAyNDQ0ODAwfQ.aJxvu2C4BASwRVqfRlA1g4Pn0ll8kiRebvH4wo396aQ",
      "params": {
        "secret": "my-secret",
        "secretFormat": "text",
        "checkExpiry": true
      },
      "output": "{\n  \"valid\": true,\n  \"algorithm\": \"HS256\",\n  \"reason\": \"signature is valid\",\n  \"expired\": false\n}"
    },
    {
      "title": "expired token",
      "input": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiZXhwIjoxMDAwMDAwMDAwfQ.08xF_XOKxxvPpUuk4mhVMMMUQ8n2oQxN5OevXj7lgVY",
      "params": {
        "secret": "my-secret",
        "secretFormat": "text",
        "checkExpiry": true
      },
      "output": "{\n  \"valid\": false,\n  \"algorithm\": \"HS256\",\n  \"reason\": \"token expired at 2001-09-09T01:46:40.000Z\",\n  \"expired\": true\n}"
    },
    {
      "title": "wrong secret",
      "input": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiZXhwIjo0MTAyNDQ0ODAwfQ.aJxvu2C4BASwRVqfRlA1g4Pn0ll8kiRebvH4wo396aQ",
      "params": {
        "secret": "wrong-secret",
        "secretFormat": "text",
        "checkExpiry": true
      },
      "output": "{\n  \"valid\": false,\n  \"algorithm\": \"HS256\",\n  \"reason\": \"signature does not match the secret\",\n  \"expired\": false\n}"
    }
  ],
  "language_detect": [
    {
      "title": "a plain English sentence",
      "input": "The quick brown fox jumps over the lazy dog near the riverbank at dawn.",
      "output": "{\n  \"code\": \"eng\",\n  \"language\": \"English\",\n  \"script\": \"Latin\",\n  \"confidence\": 0.18,\n  \"alternatives\": [\n    {\n      \"code\": \"fra\",\n      \"language\": \"French\",\n      \"score\": 0.96\n    },\n    {\n      \"code\": \"hnj\",\n      \"language\": \"Hmong Njua\",\n      \"score\": 0.87\n    },\n    {\n      \"code\": \"ind\",\n      \"language\": \"Indonesian\",\n      \"score\": 0.84\n    },\n    {\n      \"code\": \"por\",\n      \"language\": \"Portuguese\",\n      \"score\": 0.82\n    },\n    {\n      \"code\": \"ita\",\n      \"language\": \"Italian\",\n      \"score\": 0.81\n    }\n  ]\n}"
    }
  ],
  "leet": [
    {
      "title": "basic, to leet",
      "input": "leet speak",
      "params": {
        "level": "basic",
        "direction": "to-leet"
      },
      "output": "l337 5p34k"
    },
    {
      "title": "basic, decode",
      "input": "l33t sp34k",
      "params": {
        "level": "basic",
        "direction": "from-leet"
      },
      "output": "leet speak"
    }
  ],
  "length": [
    {
      "title": "a short word",
      "input": "hello",
      "output": "5"
    }
  ],
  "line_affix": [
    {
      "title": "SQL IN-list",
      "input": "apple\nbanana\ncherry",
      "params": {
        "prefix": "'",
        "suffix": "'",
        "joinWith": ", "
      },
      "output": "'apple', 'banana', 'cherry'"
    },
    {
      "title": "bullet prefix",
      "input": "a\nb",
      "params": {
        "prefix": "- "
      },
      "output": "- a\n- b"
    }
  ],
  "line_dedupe": [
    {
      "title": "default",
      "input": "a\nb\na\nc",
      "output": "a\nb\nc"
    }
  ],
  "line_reverse": [
    {
      "title": "reverse three lines",
      "input": "one\ntwo\nthree",
      "output": "three\ntwo\none"
    }
  ],
  "line_sort": [
    {
      "title": "alphabetical",
      "input": "banana\napple\ncherry",
      "output": "apple\nbanana\ncherry"
    },
    {
      "title": "natural (v2 before v10)",
      "input": "v2\nv10\nv1",
      "params": {
        "mode": "natural"
      },
      "output": "v1\nv2\nv10"
    }
  ],
  "lorem_ipsum": [
    {
      "title": "five words, starting with \"Lorem ipsum\"",
      "input": "",
      "params": {
        "unit": "words",
        "count": 5
      },
      "output": "lorem ipsum dolor sit amet"
    },
    {
      "title": "seeded sentence without the classic opener",
      "input": "",
      "params": {
        "unit": "sentences",
        "count": 1,
        "startWithLorem": false,
        "seed": 42
      },
      "output": "Cupiditate laboriosam voluptates commodo libero cupidatat assumenda commodi animi pariatur unde."
    }
  ],
  "mac_format": [
    {
      "title": "reformat as dash-separated, upper case",
      "input": "00:1a:2b:3c:4d:5e",
      "params": {
        "style": "dash",
        "case": "upper"
      },
      "output": "00-1A-2B-3C-4D-5E"
    },
    {
      "title": "address breakdown",
      "input": "00:1a:2b:3c:4d:5e",
      "params": {
        "info": true
      },
      "output": "{\n  \"address\": \"00:1a:2b:3c:4d:5e\",\n  \"bare\": \"001a2b3c4d5e\",\n  \"oui\": \"00:1a:2b\",\n  \"nic\": \"3c:4d:5e\",\n  \"bits\": 48,\n  \"isMulticast\": false,\n  \"isLocallyAdministered\": false,\n  \"isBroadcast\": false,\n  \"valid\": true\n}"
    }
  ],
  "markdown_strip": [
    {
      "title": "headings, emphasis and links",
      "input": "# Title\n\nSome **bold** and _italic_ text with a [link](https://example.com).",
      "output": "Title\n\nSome bold and italic text with a link."
    },
    {
      "title": "keep link urls and code block contents",
      "input": "# Title\n\n```js\nconst x = 1;\n```\n\nSee [docs](https://example.com/docs).",
      "params": {
        "keepLinkUrls": true,
        "keepCodeBlocks": true
      },
      "output": "Title\n\nconst x = 1;\n\nSee docs (https://example.com/docs)."
    }
  ],
  "markdown_table_format": [
    {
      "title": "pad a compact table",
      "input": "| a | bb |\n|---|---|\n| 1 | 2 |",
      "output": "| a   | bb  |\n| --- | --- |\n| 1   | 2   |"
    }
  ],
  "markdown_to_csv": [
    {
      "title": "pipe table with alignment row",
      "input": "| Name | Age |\n| --- | --- |\n| Ada | 36 |\n| Grace | 85 |",
      "output": "Name,Age\nAda,36\nGrace,85"
    }
  ],
  "markdown_to_html": [
    {
      "title": "heading, bold and a link",
      "input": "# Title\n\nSome **bold** text and a [link](https://example.com).",
      "output": "<h1>Title</h1>\n<p>Some <strong>bold</strong> text and a <a href=\"https://example.com\">link</a>.</p>\n"
    },
    {
      "title": "heading ids",
      "input": "## Sub\n\nHello",
      "params": {
        "headerIds": true
      },
      "output": "<h2 id=\"sub\">Sub</h2>\n<p>Hello</p>\n"
    }
  ],
  "md5": [
    {
      "title": "text",
      "input": "hello",
      "output": "5d41402abc4b2a76b9719d911017c592"
    },
    {
      "title": "unicode",
      "input": "café",
      "output": "07117fe4a1ebd544965dc19573183da2"
    }
  ],
  "mime_from_magic": [
    {
      "title": "a PNG signature, as hex",
      "input": "89504e470d0a1a0a",
      "inputEncoding": "hex",
      "output": "{\n  \"mime\": \"image/png\",\n  \"extension\": \"png\",\n  \"description\": \"PNG image\",\n  \"confidence\": 1\n}"
    }
  ],
  "mime_lookup": [
    {
      "title": "filename to mime type",
      "input": "report.pdf",
      "params": {
        "direction": "auto"
      },
      "output": "application/pdf"
    },
    {
      "title": "mime type to extension",
      "input": "application/json",
      "params": {
        "direction": "auto"
      },
      "output": "json"
    }
  ],
  "morse_decode": [
    {
      "title": "decode a word",
      "input": ".... . .-.. .-.. ---",
      "output": "HELLO"
    }
  ],
  "morse_encode": [
    {
      "title": "prosign",
      "input": "SOS",
      "output": "... --- ..."
    },
    {
      "title": "two words",
      "input": "Hello World",
      "output": ".... . .-.. .-.. --- / .-- --- .-. .-.. -.."
    }
  ],
  "msgpack_decode": [
    {
      "title": "decode a two-field map",
      "input": "82a2696401a46e616d65a3416461",
      "inputEncoding": "hex",
      "output": "{\n  \"id\": 1,\n  \"name\": \"Ada\"\n}"
    }
  ],
  "msgpack_encode": [
    {
      "title": "encode a two-field map",
      "input": "{\"id\":1,\"name\":\"Ada\"}",
      "inputEncoding": "json",
      "output": "bytes[130, 162, 105, 100, 01, 164, 110, 97, 109, 101, 163, 65, 100, 97]\nhex: [82, a2, 69, 64, 01, a4, 6e, 61, 6d, 65, a3, 41, 64, 61]\nutf8: ��id\u0001�name�Ada"
    }
  ],
  "multi_replace": [
    {
      "title": "find and replace pairs, applied in order",
      "input": "the colour grey",
      "params": {
        "rules": [
          [
            "colour",
            "color"
          ],
          [
            "grey",
            "gray"
          ]
        ]
      },
      "output": "the color gray"
    }
  ],
  "nanoid": [
    {
      "title": "seeded id, default alphabet",
      "input": "",
      "params": {
        "size": 10,
        "seed": 42
      },
      "output": "8KAtKTUBeB"
    },
    {
      "title": "digits-only id",
      "input": "",
      "params": {
        "size": 6,
        "alphabet": "0-9",
        "seed": 42
      },
      "output": "604587"
    }
  ],
  "ngram_frequency": [
    {
      "title": "top word bigrams",
      "input": "the cat sat on the mat",
      "params": {
        "n": 2,
        "top": 3
      },
      "output": "cat sat  1\non the   1\nsat on   1"
    }
  ],
  "normalize": [
    {
      "title": "compose a combining accent (NFC)",
      "input": "é",
      "params": {
        "form": "NFC"
      },
      "output": "é"
    },
    {
      "title": "decompose (NFD)",
      "input": "é",
      "params": {
        "form": "NFD"
      },
      "output": "é"
    }
  ],
  "normalize_line_endings": [
    {
      "title": "convert to CRLF",
      "input": "a\nb\nc",
      "params": {
        "mode": "crlf"
      },
      "output": "a\r\nb\r\nc"
    },
    {
      "title": "detect the mix",
      "input": "a\r\nb\nc",
      "params": {
        "mode": "detect"
      },
      "output": "{\n  \"crlf\": 1,\n  \"lf\": 1,\n  \"cr\": 0,\n  \"mixed\": true,\n  \"dominant\": \"crlf\"\n}"
    }
  ],
  "number_base_convert": [
    {
      "title": "decimal to hex",
      "input": "255",
      "params": {
        "from": 10,
        "to": 16
      },
      "output": "ff"
    },
    {
      "title": "auto-detect to binary",
      "input": "0xff",
      "params": {
        "from": 0,
        "to": 2
      },
      "output": "11111111"
    }
  ],
  "number_format": [
    {
      "title": "thousands",
      "input": "1234567.891",
      "params": {
        "style": "thousands",
        "decimals": 2
      },
      "output": "1,234,567.89"
    },
    {
      "title": "percent",
      "input": "0.4567",
      "params": {
        "style": "percent",
        "decimals": 1
      },
      "output": "45.7%"
    }
  ],
  "number_lines": [
    {
      "title": "default",
      "input": "a\nb\nc",
      "output": "1: a\n2: b\n3: c"
    }
  ],
  "number_sequence": [
    {
      "title": "simple range",
      "input": "",
      "params": {
        "start": 1,
        "end": 5,
        "step": 1
      },
      "output": "1\n2\n3\n4\n5"
    },
    {
      "title": "zero-padded hex with a prefix",
      "input": "",
      "params": {
        "start": 0,
        "end": 3,
        "step": 1,
        "radix": 16,
        "pad": 2,
        "prefix": "0x"
      },
      "output": "0x00\n0x01\n0x02\n0x03"
    }
  ],
  "number_words": [
    {
      "title": "cardinal to words",
      "input": "42",
      "params": {
        "direction": "to-words",
        "style": "cardinal"
      },
      "output": "forty-two"
    },
    {
      "title": "words to number",
      "input": "forty-two",
      "params": {
        "direction": "to-number",
        "style": "cardinal"
      },
      "output": "42"
    }
  ],
  "octal_decode": [
    {
      "title": "space-separated octal",
      "input": "110 145 154 154 157",
      "output": "Hello"
    },
    {
      "title": "backslash escapes to bytes",
      "input": "\\110\\145\\154\\154\\157",
      "params": {
        "output": "bytes"
      },
      "output": "bytes[72, 101, 108, 108, 111]\nhex: [48, 65, 6c, 6c, 6f]\nutf8: Hello"
    }
  ],
  "octal_encode": [
    {
      "title": "default separator",
      "input": "Hi!",
      "output": "110 151 041"
    },
    {
      "title": "custom separator",
      "input": "AB",
      "params": {
        "separator": "\\n"
      },
      "output": "101\n102"
    }
  ],
  "ordinalize": [
    {
      "title": "suffix",
      "input": "21",
      "params": {
        "style": "suffix"
      },
      "output": "21st"
    },
    {
      "title": "words",
      "input": "3",
      "params": {
        "style": "words"
      },
      "output": "third"
    }
  ],
  "pad": [
    {
      "title": "zero-pad a number",
      "input": "42",
      "params": {
        "length": 6,
        "char": "0",
        "side": "start"
      },
      "output": "000042"
    },
    {
      "title": "center with dashes",
      "input": "hi",
      "params": {
        "length": 6,
        "char": "-",
        "side": "both"
      },
      "output": "--hi--"
    }
  ],
  "password_generator": [
    {
      "title": "seeded random password",
      "input": "",
      "params": {
        "mode": "random",
        "length": 16,
        "seed": 42
      },
      "output": "nm7U=L&9*MvKtqHs"
    },
    {
      "title": "seeded passphrase",
      "input": "",
      "params": {
        "mode": "passphrase",
        "words": 4,
        "seed": 42
      },
      "output": "Coyote6-Chase-Errand-Dance%"
    }
  ],
  "pbkdf2": [
    {
      "title": "hex output",
      "input": "password",
      "params": {
        "algorithm": "SHA-256",
        "salt": "salt",
        "iterations": 1000,
        "keyLength": 16,
        "output": "hex"
      },
      "output": "632c2812e46d4604102ba7618e9d6d7d"
    },
    {
      "title": "base64 output",
      "input": "password",
      "params": {
        "algorithm": "SHA-256",
        "salt": "salt",
        "iterations": 1000,
        "keyLength": 16,
        "output": "base64"
      },
      "output": "YywoEuRtRgQQK6dhjp1tfQ=="
    }
  ],
  "pluralize_words": [
    {
      "title": "pluralize the last word",
      "input": "I have one cat and two dog",
      "params": {
        "mode": "plural",
        "scope": "last-word",
        "count": 0
      },
      "output": "I have one cat and two dogs"
    },
    {
      "title": "count prefixes the whole phrase",
      "input": "apple",
      "params": {
        "mode": "plural",
        "scope": "whole",
        "count": 3
      },
      "output": "3 apples"
    }
  ],
  "protobuf_decode": [
    {
      "title": "varint + string fields",
      "input": "089601120568656c6c6f",
      "inputEncoding": "hex",
      "output": "[\n  {\n    \"field\": 1,\n    \"wireType\": 0,\n    \"value\": 150\n  },\n  {\n    \"field\": 2,\n    \"wireType\": 2,\n    \"value\": \"hello\"\n  }\n]"
    },
    {
      "title": "single length-delimited field",
      "input": "0a03666f6f",
      "inputEncoding": "hex",
      "output": "[\n  {\n    \"field\": 1,\n    \"wireType\": 2,\n    \"value\": \"foo\"\n  }\n]"
    }
  ],
  "punycode_decode": [
    {
      "title": "single label",
      "input": "xn--nxasmq6b",
      "params": {
        "mode": "label"
      },
      "output": "βόλοσ"
    },
    {
      "title": "whole domain",
      "input": "xn--nxasmq6b.example.com",
      "output": "βόλοσ.example.com"
    },
    {
      "title": "raw bootstring",
      "input": "4can8av2009b",
      "params": {
        "mode": "raw"
      },
      "output": "üëäö♥"
    }
  ],
  "punycode_encode": [
    {
      "title": "domain",
      "input": "münchen.de",
      "output": "xn--mnchen-3ya.de"
    },
    {
      "title": "raw bootstring",
      "input": "café",
      "params": {
        "mode": "raw"
      },
      "output": "caf-dma"
    }
  ],
  "qr_code": [
    {
      "title": "JSON module matrix for a short string",
      "input": "HI",
      "params": {
        "errorCorrection": "L",
        "output": "json"
      },
      "output": "{\n  \"text\": \"HI\",\n  \"version\": 1,\n  \"errorCorrection\": \"L\",\n  \"moduleCount\": 21,\n  \"moduleSize\": 4,\n  \"margin\": 4,\n  \"dark\": \"#000000\",\n  \"light\": \"#ffffff\",\n  \"rows\": [\n    \"111111100100101111111\",\n    \"100000101001001000001\",\n    \"101110100100001011101\",\n    \"101110101001001011101\",\n    \"101110100011101011101\",\n    \"100000101110101000001\",\n    \"111111101010101111111\",\n    \"000000000011100000000\",\n    \"111110111100110101010\",\n    \"011101001110100100000\",\n    \"000001110001010011110\",\n    \"001100010010000110100\",\n    \"100001110001010010101\",\n    \"000000001011111001000\",\n    \"111111101000101100010\",\n    \"100000100101111001001\",\n    \"101110101010100100100\",\n    \"101110101110100100100\",\n    \"101110101001010011100\",\n    \"100000101000000110100\",\n    \"111111101111010011110\"\n  ]\n}"
    }
  ],
  "query_params_normalize": [
    {
      "title": "sort, lowercase host, drop utm_*",
      "input": "https://Example.com/path?b=2&a=1&utm_source=x",
      "params": {
        "drop": "utm_*"
      },
      "output": "https://example.com/path?a=1&b=2"
    }
  ],
  "query_string_to_json": [
    {
      "title": "repeated key becomes an array, values typed",
      "input": "a=1&b=2&b=3",
      "params": {
        "nested": "auto",
        "typed": true,
        "indent": 2
      },
      "output": "{\n  \"a\": 1,\n  \"b\": [\n    2,\n    3\n  ]\n}"
    }
  ],
  "quoted_printable_decode": [
    {
      "title": "hex escape",
      "input": "Caf=C3=A9",
      "output": "Café"
    },
    {
      "title": "soft line break",
      "input": "Line one=\r\nstill line one",
      "output": "Line onestill line one"
    }
  ],
  "quoted_printable_encode": [
    {
      "title": "non-ASCII and =",
      "input": "café = caffeine?",
      "output": "caf=C3=A9 =3D caffeine?"
    },
    {
      "title": "wrapped at a short line length",
      "input": "abcdefghijklmnopqrstuvwxyz",
      "params": {
        "lineLength": 10
      },
      "output": "abcdefghi=\r\njklmnopqr=\r\nstuvwxyz"
    }
  ],
  "rail_fence_decode": [
    {
      "title": "decode with 3 rails",
      "input": "WECRLTEERDSOEEFEAOCAIVDEN",
      "params": {
        "rails": 3,
        "offset": 0
      },
      "output": "WEAREDISCOVEREDFLEEATONCE"
    }
  ],
  "rail_fence_encode": [
    {
      "title": "encode with 3 rails",
      "input": "WEAREDISCOVEREDFLEEATONCE",
      "params": {
        "rails": 3,
        "offset": 0
      },
      "output": "WECRLTEERDSOEEFEAOCAIVDEN"
    }
  ],
  "random_bytes": [
    {
      "title": "seeded bytes as hex",
      "input": "",
      "params": {
        "count": 8,
        "output": "hex",
        "seed": 42
      },
      "output": "9972daab2c86459f"
    },
    {
      "title": "same bytes as a C array",
      "input": "",
      "params": {
        "count": 4,
        "output": "c-array",
        "seed": 42
      },
      "output": "uint8_t data[4] = { 0x99, 0x72, 0xda, 0xab };"
    }
  ],
  "random_case": [
    {
      "title": "seeded",
      "input": "hello world",
      "params": {
        "seed": 1,
        "probability": 0.5
      },
      "output": "hEllo WorLd"
    }
  ],
  "random_string": [
    {
      "title": "seeded alphanumeric string",
      "input": "",
      "params": {
        "length": 12,
        "seed": 42
      },
      "output": "KESvO50HW7tf"
    },
    {
      "title": "seeded hex string",
      "input": "",
      "params": {
        "length": 8,
        "charset": "hex",
        "seed": 42
      },
      "output": "ca0da341"
    }
  ],
  "readability": [
    {
      "title": "two simple sentences",
      "input": "The cat sat on the mat. It was a sunny day.",
      "output": "{\n  \"fleschReadingEase\": 100,\n  \"fleschReadingEaseLabel\": \"very easy\",\n  \"fleschKincaidGrade\": 0,\n  \"gunningFog\": 2.2,\n  \"smog\": 3.13,\n  \"colemanLiau\": 0,\n  \"automatedReadabilityIndex\": 0,\n  \"averageGrade\": 1.07,\n  \"readingLevel\": \"elementary school\",\n  \"words\": 11,\n  \"sentences\": 2,\n  \"syllables\": 12,\n  \"characters\": 43,\n  \"letters\": 31,\n  \"complexWords\": 0,\n  \"polysyllabicWords\": 0,\n  \"avgWordsPerSentence\": 5.5,\n  \"avgSyllablesPerWord\": 1.09,\n  \"avgLettersPerWord\": 2.82\n}"
    }
  ],
  "reading_time": [
    {
      "title": "a short paragraph",
      "input": "The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog.",
      "output": "2 min read (360 words at 200 wpm)"
    }
  ],
  "regex_explain": [
    {
      "title": "a date-like pattern",
      "input": "",
      "params": {
        "pattern": "^(\\d{4})-(\\d{2})$"
      },
      "output": "pattern:   /^(\\d{4})-(\\d{2})$/\nflags:     (none)\n\n^        —  the start of the string (or of a line when the m flag is set)\n( … )    —  capturing group 1\n  \\d{4}  —  any digit (0-9), repeated exactly 4 times\n-        —  the character \"-\"\n( … )    —  capturing group 2\n  \\d{2}  —  any digit (0-9), repeated exactly 2 times\n$        —  the end of the string (or of a line when the m flag is set)\n\ncapture groups: 1, 2"
    }
  ],
  "regex_extract": [
    {
      "title": "extract all numbers",
      "input": "abc 123 def 456",
      "params": {
        "pattern": "\\d+",
        "flags": "g"
      },
      "output": "123\n456"
    },
    {
      "title": "case-insensitive match",
      "input": "Hello WORLD hello",
      "params": {
        "pattern": "hello",
        "flags": "gi"
      },
      "output": "Hello\nhello"
    }
  ],
  "remove_blank_lines": [
    {
      "title": "blank and whitespace-only lines",
      "input": "a\n\nb\n   \nc",
      "output": "a\nb\nc"
    }
  ],
  "remove_invisible": [
    {
      "title": "list zero-width spaces",
      "input": "a​b​c",
      "params": {
        "mode": "list"
      },
      "output": "[\n  {\n    \"codePoint\": \"U+200B\",\n    \"name\": \"ZERO WIDTH SPACE\",\n    \"index\": 1\n  },\n  {\n    \"codePoint\": \"U+200B\",\n    \"name\": \"ZERO WIDTH SPACE\",\n    \"index\": 3\n  }\n]"
    },
    {
      "title": "remove them",
      "input": "a​b",
      "params": {
        "mode": "remove"
      },
      "output": "ab"
    }
  ],
  "repeat": [
    {
      "title": "repeat with a separator",
      "input": "ab",
      "params": {
        "count": 3,
        "separator": "-"
      },
      "output": "ab-ab-ab"
    }
  ],
  "replace": [
    {
      "title": "literal replace",
      "input": "foo bar foo",
      "params": {
        "pattern": "foo",
        "replacement": "baz",
        "regex": false,
        "flags": "g"
      },
      "output": "baz bar baz"
    },
    {
      "title": "regex with a capture group",
      "input": "foo1 foo2",
      "params": {
        "pattern": "foo(\\d)",
        "replacement": "F$1",
        "regex": true,
        "flags": "g"
      },
      "output": "F1 F2"
    }
  ],
  "reverse": [
    {
      "title": "reverse a word",
      "input": "hello",
      "output": "olleh"
    }
  ],
  "reverse_words": [
    {
      "title": "reverse word order per line",
      "input": "the quick brown fox",
      "output": "fox brown quick the"
    }
  ],
  "roman_numerals": [
    {
      "title": "to roman",
      "input": "1994",
      "params": {
        "direction": "to-roman"
      },
      "output": "MCMXCIV"
    },
    {
      "title": "to arabic",
      "input": "MCMXCIV",
      "params": {
        "direction": "to-arabic"
      },
      "output": "1994"
    }
  ],
  "rot13": [
    {
      "title": "basic",
      "input": "Hello, World!",
      "output": "Uryyb, Jbeyq!"
    }
  ],
  "sed": [
    {
      "title": "global substitute per line",
      "input": "foo bar\nbaz foo",
      "params": {
        "script": "s/foo/QUX/g",
        "perLine": true
      },
      "output": "QUX bar\nbaz QUX"
    }
  ],
  "semver": [
    {
      "title": "parse a version with prerelease and build",
      "input": "1.2.3-beta.1+build.5",
      "params": {
        "mode": "parse"
      },
      "output": "{\n  \"raw\": \"1.2.3-beta.1+build.5\",\n  \"version\": \"1.2.3-beta.1\",\n  \"valid\": true,\n  \"major\": 1,\n  \"minor\": 2,\n  \"patch\": 3,\n  \"prerelease\": [\n    \"beta\",\n    1\n  ],\n  \"build\": [\n    \"build\",\n    \"5\"\n  ],\n  \"isPrerelease\": true,\n  \"isStable\": false\n}"
    },
    {
      "title": "compare two versions",
      "input": "1.2.3",
      "params": {
        "mode": "compare",
        "other": "1.3.0"
      },
      "output": "{\n  \"a\": \"1.2.3\",\n  \"b\": \"1.3.0\",\n  \"result\": -1,\n  \"relation\": \"lt\",\n  \"description\": \"1.2.3 < 1.3.0\",\n  \"equalPrecedence\": false\n}"
    },
    {
      "title": "test against a caret range",
      "input": "1.4.2",
      "params": {
        "mode": "satisfies",
        "range": "^1.2.0"
      },
      "output": "{\n  \"version\": \"1.4.2\",\n  \"range\": \"^1.2.0\",\n  \"satisfies\": true\n}"
    }
  ],
  "set_operations": [
    {
      "title": "intersection",
      "input": "a\nb\nc",
      "params": {
        "other": "b\nc\nd",
        "operation": "intersection"
      },
      "output": "b\nc"
    },
    {
      "title": "sorted union",
      "input": "a\nb\nc",
      "params": {
        "other": "b\nc\nd",
        "operation": "union",
        "sort": true
      },
      "output": "a\nb\nc\nd"
    }
  ],
  "sha3": [
    {
      "title": "SHA3-256",
      "input": "hello",
      "params": {
        "algorithm": "SHA3-256",
        "output": "hex"
      },
      "output": "3338be694f50c5f338814986cdf0686453a888b84f424d792af4b9202398f392"
    },
    {
      "title": "Keccak-256",
      "input": "hello",
      "params": {
        "algorithm": "Keccak-256",
        "output": "hex"
      },
      "output": "1c8aff950685c2ed4bc3174f3472287b56d9517b9c948127319a09a7a36deac8"
    }
  ],
  "shell_quote": [
    {
      "title": "posix single-quote",
      "input": "it's a test",
      "params": {
        "flavor": "posix",
        "mode": "quote"
      },
      "output": "'it'\\''s a test'"
    },
    {
      "title": "powershell single-quote",
      "input": "hello world",
      "params": {
        "flavor": "powershell",
        "mode": "quote"
      },
      "output": "'hello world'"
    }
  ],
  "shuffle": [
    {
      "title": "seeded word shuffle",
      "input": "the quick brown fox",
      "params": {
        "unit": "words",
        "seed": 42
      },
      "output": "the fox quick brown"
    },
    {
      "title": "seeded line shuffle",
      "input": "one\ntwo\nthree\nfour",
      "params": {
        "unit": "lines",
        "seed": 42
      },
      "output": "one\nfour\ntwo\nthree"
    }
  ],
  "slice": [
    {
      "title": "slice a substring",
      "input": "Hello World",
      "params": {
        "start": 6,
        "end": 11
      },
      "output": "World"
    }
  ],
  "slug": [
    {
      "title": "accents and punctuation",
      "input": "Héllo, World!  Ünïcode",
      "output": "hello-world-unicode"
    }
  ],
  "smart_quotes": [
    {
      "title": "to smart",
      "input": "He said \"it's here\" -- really...",
      "params": {
        "direction": "to-smart"
      },
      "output": "He said “it’s here” – really…"
    },
    {
      "title": "to straight",
      "input": "“He said” ‘it’s here’ — really…",
      "params": {
        "direction": "to-straight"
      },
      "output": "\"He said\" 'it's here' --- really..."
    }
  ],
  "sort_words_in_line": [
    {
      "title": "ascending",
      "input": "banana apple cherry",
      "output": "apple banana cherry"
    },
    {
      "title": "unique words",
      "input": "c b a b",
      "params": {
        "unique": true
      },
      "output": "a b c"
    }
  ],
  "split_join": [
    {
      "title": "commas to pipes",
      "input": "a,b,c",
      "params": {
        "splitBy": ",",
        "joinWith": " | "
      },
      "output": "a | b | c"
    }
  ],
  "sql_escape": [
    {
      "title": "ansi quote doubling",
      "input": "O'Brien",
      "params": {
        "flavor": "ansi",
        "wrap": true
      },
      "output": "'O''Brien'"
    },
    {
      "title": "mysql backslash escapes",
      "input": "O'Brien",
      "params": {
        "flavor": "mysql",
        "wrap": true
      },
      "output": "'O\\'Brien'"
    }
  ],
  "sql_format": [
    {
      "title": "default dialect, upper keywords",
      "input": "select a,b from t where a=1",
      "output": "SELECT\n  a,\n  b\nFROM\n  t\nWHERE\n  a = 1"
    }
  ],
  "sql_minify": [
    {
      "title": "strip comments and collapse",
      "input": "SELECT a, b\nFROM t -- comment\nWHERE a = 1;",
      "output": "SELECT a, b FROM t WHERE a = 1;"
    }
  ],
  "string_distance": [
    {
      "title": "kitten vs sitting",
      "input": "kitten",
      "params": {
        "other": "sitting",
        "algorithm": "levenshtein"
      },
      "output": "{\n  \"algorithm\": \"levenshtein\",\n  \"distance\": 3,\n  \"similarity\": 0.571429,\n  \"a\": \"kitten\",\n  \"b\": \"sitting\"\n}"
    }
  ],
  "strip_ansi": [
    {
      "title": "strip SGR color codes",
      "input": "\u001b[31mred\u001b[0m text",
      "params": {
        "mode": "strip"
      },
      "output": "red text"
    }
  ],
  "strip_chars": [
    {
      "title": "strip punctuation",
      "input": "Hello, World! 123",
      "params": {
        "type": "punctuation",
        "custom": "",
        "invert": false,
        "replaceWith": ""
      },
      "output": "Hello World 123"
    }
  ],
  "strip_html_tags": [
    {
      "title": "paragraphs to plain text",
      "input": "<p>Hello <b>World</b></p><p>Bye</p>",
      "output": "Hello World\n\nBye"
    }
  ],
  "substring_around": [
    {
      "title": "domain after @",
      "input": "user@example.com",
      "params": {
        "delimiter": "@",
        "mode": "after",
        "endDelimiter": "",
        "occurrence": "first",
        "perLine": false,
        "ifMissing": "whole"
      },
      "output": "example.com"
    }
  ],
  "swap_case": [
    {
      "title": "default",
      "input": "Hello World",
      "output": "hELLO wORLD"
    }
  ],
  "tabs_spaces": [
    {
      "title": "tabs to spaces",
      "input": "\tfoo\tbar",
      "output": "    foo bar"
    },
    {
      "title": "spaces to tabs",
      "input": "        indented",
      "params": {
        "direction": "spaces-to-tabs"
      },
      "output": "\t\tindented"
    }
  ],
  "tail": [
    {
      "title": "last 2 lines",
      "input": "one\ntwo\nthree\nfour\nfive",
      "params": {
        "count": 2,
        "unit": "lines"
      },
      "output": "four\nfive"
    }
  ],
  "template_expand": [
    {
      "title": "numbered rows",
      "input": "",
      "params": {
        "template": "row-{i}",
        "count": 3
      },
      "output": "row-1\nrow-2\nrow-3"
    },
    {
      "title": "seeded random integers",
      "input": "",
      "params": {
        "template": "{i}: {randint:1,100}",
        "count": 3,
        "seed": 42
      },
      "output": "1: 61\n2: 45\n3: 86"
    }
  ],
  "text_diff": [
    {
      "title": "one changed line",
      "input": "line one\nline two\n",
      "params": {
        "other": "line one\nline TWO\n"
      },
      "output": "@@ -1,2 +1,2 @@\n line one\n-line two\n+line TWO"
    }
  ],
  "text_stats": [
    {
      "title": "a short paragraph",
      "input": "Hello world. This is great!",
      "output": "{\n  \"characters\": 27,\n  \"charactersNoSpaces\": 23,\n  \"graphemes\": 27,\n  \"words\": 5,\n  \"uniqueWords\": 5,\n  \"sentences\": 2,\n  \"paragraphs\": 1,\n  \"lines\": 1,\n  \"nonEmptyLines\": 1,\n  \"bytesUtf8\": 27,\n  \"bytesUtf16\": 54,\n  \"avgWordLength\": 4.2,\n  \"avgWordsPerSentence\": 2.5,\n  \"longestWord\": \"Hello\",\n  \"longestLine\": 27\n}"
    }
  ],
  "timestamp_convert": [
    {
      "title": "unix seconds to ISO",
      "input": "1710494400",
      "params": {
        "to": "iso"
      },
      "output": "2024-03-15T09:20:00.000Z"
    },
    {
      "title": "ISO to unix seconds",
      "input": "2024-03-15T09:30:00Z",
      "params": {
        "to": "unix"
      },
      "output": "1710495000"
    }
  ],
  "timestamp_now": [
    {
      "title": "current time as ISO 8601",
      "input": "",
      "params": {
        "format": "iso"
      },
      "outputMatches": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$"
    },
    {
      "title": "current time as unix seconds",
      "input": "",
      "params": {
        "format": "unix"
      },
      "outputMatches": "^\\d{9,10}$"
    }
  ],
  "toml_to_json": [
    {
      "title": "table becomes a nested object",
      "input": "name = \"example\"\nport = 8080\n[owner]\nname = \"Bob\"",
      "output": "{\n  \"name\": \"example\",\n  \"port\": 8080,\n  \"owner\": {\n    \"name\": \"Bob\"\n  }\n}"
    },
    {
      "title": "minified",
      "input": "name = \"x\"",
      "params": {
        "indent": 0
      },
      "output": "{\"name\":\"x\"}"
    }
  ],
  "tr": [
    {
      "title": "uppercase via a-z range",
      "input": "hello world",
      "params": {
        "from": "a-z",
        "to": "A-Z",
        "delete": false,
        "squeeze": false,
        "ranges": true
      },
      "output": "HELLO WORLD"
    }
  ],
  "trim": [
    {
      "title": "trim surrounding spaces",
      "input": "   padded text   ",
      "output": "padded text"
    }
  ],
  "trim_lines": [
    {
      "title": "trim both sides",
      "input": "  hello  \n  world  ",
      "output": "hello\nworld"
    }
  ],
  "truncate": [
    {
      "title": "longer than the limit",
      "input": "Hello, World! This is a test.",
      "params": {
        "length": 15
      },
      "output": "Hello, World! …"
    },
    {
      "title": "already short enough",
      "input": "Hi",
      "params": {
        "length": 15
      },
      "output": "Hi"
    }
  ],
  "ulid": [
    {
      "title": "seeded ulid at a fixed timestamp",
      "input": "",
      "params": {
        "timestamp": 1700000000000,
        "seed": 42
      },
      "output": "01HF7YAT00XXY75GSBHBD3PCP0"
    },
    {
      "title": "a monotonic batch of three",
      "input": "",
      "params": {
        "count": 3,
        "timestamp": 1700000000000,
        "seed": 42
      },
      "output": "01HF7YAT00XXY75GSBHBD3PCP0\n01HF7YAT00XXY75GSBHBD3PCP1\n01HF7YAT00XXY75GSBHBD3PCP2"
    }
  ],
  "unescape_html": [
    {
      "title": "basic entities",
      "input": "Tom &amp; Jerry &lt;3&gt;",
      "output": "Tom & Jerry <3>"
    },
    {
      "title": "quotes",
      "input": "It&#39;s &quot;fine&quot;",
      "output": "It's \"fine\""
    }
  ],
  "unicode_escape_decode": [
    {
      "title": "JS/Java \\u escapes",
      "input": "\\u0041\\u0042\\u0043",
      "output": "ABC"
    },
    {
      "title": "ES2015 brace escape",
      "input": "\\u{1F600}",
      "output": "😀"
    },
    {
      "title": "HTML entities",
      "input": "&#x1F600; &#128512;",
      "output": "😀 😀"
    }
  ],
  "unicode_escape_encode": [
    {
      "title": "non-ASCII, default style",
      "input": "café 日本語",
      "output": "caf\\u00e9 \\u65e5\\u672c\\u8a9e"
    },
    {
      "title": "every character, CSS style",
      "input": "Hi!",
      "params": {
        "style": "css",
        "scope": "all"
      },
      "output": "\\48 \\69 \\21 "
    }
  ],
  "unicode_inspect": [
    {
      "title": "letters, an accent and an emoji",
      "input": "Aé😀",
      "params": {
        "limit": 5
      },
      "output": "#  CHAR  CODE POINT  DEC     UTF-8        UTF-16     GC  CATEGORY          SCRIPT  BLOCK               FLAGS\n0  A     U+0041      65      41           0041       Lu  Uppercase Letter  Latin   Basic Latin\n1  é     U+00E9      233     C3 A9        00E9       Ll  Lowercase Letter  Latin   Latin-1 Supplement\n2  😀    U+1F600     128512  F0 9F 98 80  D83D DE00  So  Other Symbol      Common  Emoticons           emoji"
    }
  ],
  "unicode_style": [
    {
      "title": "bold",
      "input": "Hello",
      "params": {
        "style": "bold"
      },
      "output": "𝐇𝐞𝐥𝐥𝐨"
    },
    {
      "title": "small caps",
      "input": "Hello World",
      "params": {
        "style": "small-caps"
      },
      "output": "ʜᴇʟʟᴏ ᴡᴏʀʟᴅ"
    },
    {
      "title": "zalgo, seeded for reproducible output",
      "input": "cursed",
      "params": {
        "style": "zalgo",
        "intensity": 5,
        "seed": 42
      },
      "outputMatches": "^c[\\s\\S]+d[\\s\\S]*$"
    }
  ],
  "uniq_count": [
    {
      "title": "count-desc",
      "input": "a\nb\na\nc\nb\na",
      "output": "3\ta\n2\tb\n1\tc"
    },
    {
      "title": "json",
      "input": "a\nb\na\nc\nb\na",
      "params": {
        "format": "json"
      },
      "output": "{\n  \"totalLines\": 6,\n  \"uniqueLines\": 3,\n  \"entries\": [\n    {\n      \"line\": \"a\",\n      \"count\": 3\n    },\n    {\n      \"line\": \"b\",\n      \"count\": 2\n    },\n    {\n      \"line\": \"c\",\n      \"count\": 1\n    }\n  ]\n}"
    }
  ],
  "unwrap": [
    {
      "title": "joins a soft-wrapped paragraph",
      "input": "This is a\nwrapped paragraph.",
      "output": "This is a wrapped paragraph."
    },
    {
      "title": "keeps list items and blank-line breaks",
      "input": "Notes:\n\n- first point\n  continued\n- second point",
      "output": "Notes:\n\n- first point continued\n- second point"
    }
  ],
  "url_build": [
    {
      "title": "assemble from protocol/host/path/query",
      "input": "{\"protocol\":\"https\",\"host\":\"example.com\",\"pathname\":\"/a/b\",\"searchParams\":{\"x\":\"1\"}}",
      "params": {
        "encode": true
      },
      "output": "https://example.com/a/b?x=1"
    }
  ],
  "url_decode": [
    {
      "title": "percent-decode",
      "input": "hello%20world%21",
      "output": "hello world!"
    },
    {
      "title": "unicode",
      "input": "caf%C3%A9",
      "output": "café"
    }
  ],
  "url_encode": [
    {
      "title": "reserved characters",
      "input": "hello world!",
      "output": "hello%20world!"
    },
    {
      "title": "unicode",
      "input": "café",
      "output": "caf%C3%A9"
    }
  ],
  "url_parse": [
    {
      "title": "full URL with auth, query and hash",
      "input": "https://user:pw@example.com:8080/a/b?x=1&y=2#frag",
      "output": "{\n  \"href\": \"https://user:pw@example.com:8080/a/b?x=1&y=2#frag\",\n  \"protocol\": \"https:\",\n  \"username\": \"user\",\n  \"password\": \"pw\",\n  \"host\": \"example.com:8080\",\n  \"hostname\": \"example.com\",\n  \"port\": \"8080\",\n  \"pathname\": \"/a/b\",\n  \"pathSegments\": [\n    \"a\",\n    \"b\"\n  ],\n  \"search\": \"?x=1&y=2\",\n  \"searchParams\": {\n    \"x\": \"1\",\n    \"y\": \"2\"\n  },\n  \"hash\": \"#frag\",\n  \"origin\": \"https://example.com:8080\",\n  \"isAbsolute\": true\n}"
    }
  ],
  "user_agent_parse": [
    {
      "title": "desktop Chrome on Windows",
      "input": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
      "output": "{\n  \"browser\": {\n    \"name\": \"Chrome\",\n    \"version\": \"117.0.0.0\",\n    \"major\": \"117\",\n    \"type\": null\n  },\n  \"engine\": {\n    \"name\": \"Blink\",\n    \"version\": \"117.0.0.0\"\n  },\n  \"os\": {\n    \"name\": \"Windows\",\n    \"version\": \"10\"\n  },\n  \"device\": {\n    \"type\": \"desktop\",\n    \"vendor\": null,\n    \"model\": null\n  },\n  \"cpu\": {\n    \"architecture\": \"amd64\"\n  },\n  \"isBot\": false\n}"
    },
    {
      "title": "a crawler",
      "input": "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
      "output": "{\n  \"browser\": {\n    \"name\": \"Googlebot\",\n    \"version\": \"2.1\",\n    \"major\": \"2\",\n    \"type\": \"crawler\"\n  },\n  \"engine\": {\n    \"name\": null,\n    \"version\": null\n  },\n  \"os\": {\n    \"name\": null,\n    \"version\": null\n  },\n  \"device\": {\n    \"type\": null,\n    \"vendor\": null,\n    \"model\": null\n  },\n  \"cpu\": {\n    \"architecture\": null\n  },\n  \"isBot\": true\n}"
    }
  ],
  "uuid": [
    {
      "title": "nil uuid",
      "input": "",
      "params": {
        "version": "nil"
      },
      "output": "00000000-0000-0000-0000-000000000000"
    },
    {
      "title": "max uuid, uppercase with braces",
      "input": "",
      "params": {
        "version": "max",
        "uppercase": true,
        "braces": true
      },
      "output": "{FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF}"
    },
    {
      "title": "seeded v4 uuid",
      "input": "",
      "params": {
        "version": "v4",
        "seed": 42
      },
      "output": "8a2bc372-c032-4bda-adb0-73ab8a9ac02c"
    }
  ],
  "validate": [
    {
      "title": "a valid email",
      "input": "user@example.com",
      "params": {
        "type": "email"
      },
      "output": "{\n  \"type\": \"email\",\n  \"value\": \"user@example.com\",\n  \"valid\": true,\n  \"reason\": \"valid email address\",\n  \"normalized\": \"user@example.com\"\n}"
    },
    {
      "title": "an invalid email",
      "input": "not-an-email",
      "params": {
        "type": "email"
      },
      "output": "{\n  \"type\": \"email\",\n  \"value\": \"not-an-email\",\n  \"valid\": false,\n  \"reason\": \"missing \\\"@\\\"\"\n}"
    }
  ],
  "vigenere_decode": [
    {
      "title": "decode with key LEMON",
      "input": "LXFOPVEFRNHR",
      "params": {
        "key": "LEMON",
        "preserveCase": true,
        "skipNonLetters": true
      },
      "output": "ATTACKATDAWN"
    }
  ],
  "vigenere_encode": [
    {
      "title": "encode with key LEMON",
      "input": "ATTACKATDAWN",
      "params": {
        "key": "LEMON",
        "preserveCase": true,
        "skipNonLetters": true
      },
      "output": "LXFOPVEFRNHR"
    }
  ],
  "word_frequency": [
    {
      "title": "top 3 words",
      "input": "the cat sat on the mat the cat ran",
      "params": {
        "top": 3
      },
      "output": "the  3\ncat  2\nmat  1"
    }
  ],
  "word_wrap": [
    {
      "title": "wrap to 20 columns",
      "input": "The quick brown fox jumps over the lazy dog",
      "params": {
        "width": 20
      },
      "output": "The quick brown fox\njumps over the lazy\ndog"
    }
  ],
  "xml_escape": [
    {
      "title": "markup and quotes",
      "input": "<a href=\"x\">Tom & Jerry's</a>",
      "output": "&lt;a href=&quot;x&quot;&gt;Tom &amp; Jerry&apos;s&lt;/a&gt;"
    },
    {
      "title": "non-ASCII as numeric references",
      "input": "café <tag>",
      "params": {
        "scope": "non-ascii"
      },
      "output": "caf&#xE9; &lt;tag&gt;"
    }
  ],
  "xml_minify": [
    {
      "title": "strips indentation whitespace",
      "input": "<root>\n  <item>value</item>\n</root>",
      "output": "<root><item>value</item></root>"
    },
    {
      "title": "removes comments",
      "input": "<a>\n  <!-- note -->\n  <b>1</b>\n</a>",
      "output": "<a><b>1</b></a>"
    }
  ],
  "xml_pretty": [
    {
      "title": "indents nested elements",
      "input": "<root><a>1</a><b/></root>",
      "output": "<root>\n  <a>1</a>\n  <b/>\n</root>"
    }
  ],
  "xml_to_json": [
    {
      "title": "attribute + child element",
      "input": "<user id=\"1\"><name>Ann</name></user>",
      "output": "{\n  \"user\": {\n    \"@id\": \"1\",\n    \"name\": \"Ann\"\n  }\n}"
    },
    {
      "title": "string output",
      "input": "<a>1</a>",
      "params": {
        "output": "string",
        "indent": 2
      },
      "output": "{\n  \"a\": \"1\"\n}"
    }
  ],
  "xml_unescape": [
    {
      "title": "predefined entities",
      "input": "&lt;a&gt;Tom &amp; Jerry&lt;/a&gt;",
      "output": "<a>Tom & Jerry</a>"
    },
    {
      "title": "numeric references",
      "input": "x&#65;&#x42;y",
      "output": "xABy"
    }
  ],
  "xor_cipher": [
    {
      "title": "encrypt to hex with a text key",
      "input": "Attack at dawn",
      "params": {
        "key": "lemon",
        "keyFormat": "text",
        "output": "hex"
      },
      "output": "2d11190e0d07450c1b4e08041a01"
    },
    {
      "title": "encrypt to base64 with a text key",
      "input": "Attack at dawn",
      "params": {
        "key": "lemon",
        "keyFormat": "text",
        "output": "base64"
      },
      "output": "LREZDg0HRQwbTggEGgE="
    }
  ],
  "yaml_to_json": [
    {
      "title": "mapping to object",
      "input": "name: Ann\nage: 30",
      "output": "{\n  \"name\": \"Ann\",\n  \"age\": 30\n}"
    },
    {
      "title": "multi-document stream",
      "input": "---\na: 1\n---\nb: 2",
      "params": {
        "allDocuments": true
      },
      "output": "[\n  {\n    \"a\": 1\n  },\n  {\n    \"b\": 2\n  }\n]"
    }
  ],
  "zip_extract": [
    {
      "title": "extract a named entry as text",
      "input": "504b030414000000080039a9375df083a9ec0d0000000b0000000900000068656c6c6f2e747874f348cdc9c9d75188f20c500400504b030414000000080039a9375dcfbe36e00b000000090000000e000000646f63732f726561646d652e6d645356084a4d4cc94de50200504b0102140014000000080039a9375df083a9ec0d0000000b00000009000000000000000000000000000000000068656c6c6f2e747874504b0102140014000000080039a9375dcfbe36e00b000000090000000e0000000000000000000000000034000000646f63732f726561646d652e6d64504b05060000000002000200730000006b0000000000",
      "inputEncoding": "hex",
      "params": {
        "entry": "hello.txt",
        "output": "text"
      },
      "output": "Hello, ZIP!"
    }
  ],
  "zip_list": [
    {
      "title": "list a two-file archive",
      "input": "504b030414000000080039a9375df083a9ec0d0000000b0000000900000068656c6c6f2e747874f348cdc9c9d75188f20c500400504b030414000000080039a9375dcfbe36e00b000000090000000e000000646f63732f726561646d652e6d645356084a4d4cc94de50200504b0102140014000000080039a9375df083a9ec0d0000000b00000009000000000000000000000000000000000068656c6c6f2e747874504b0102140014000000080039a9375dcfbe36e00b000000090000000e0000000000000000000000000034000000646f63732f726561646d652e6d64504b05060000000002000200730000006b0000000000",
      "inputEncoding": "hex",
      "output": "{\n  \"count\": 2,\n  \"totalSize\": 20,\n  \"totalCompressedSize\": 24,\n  \"entries\": [\n    {\n      \"name\": \"hello.txt\",\n      \"size\": 11,\n      \"compressedSize\": 13,\n      \"method\": \"deflate\",\n      \"directory\": false\n    },\n    {\n      \"name\": \"docs/readme.md\",\n      \"size\": 9,\n      \"compressedSize\": 11,\n      \"method\": \"deflate\",\n      \"directory\": false\n    }\n  ]\n}"
    }
  ]
}
