// AUTO-GENERATED by scripts/gen-utilities.ts — do not edit. Run `npm run gen`.
import type { Utility } from '../../types/utility'
import u0 from '../aes_decrypt/index'
import u1 from '../aes_encrypt/index'
import u2 from '../align_columns/index'
import u3 from '../alternating_case/index'
import u4 from '../argon2_hash/index'
import u5 from '../ascii_banner/index'
import u6 from '../atbash/index'
import u7 from '../base32_decode/index'
import u8 from '../base32_encode/index'
import u9 from '../base58_decode/index'
import u10 from '../base58_encode/index'
import u11 from '../base62_decode/index'
import u12 from '../base62_encode/index'
import u13 from '../base64_decode/index'
import u14 from '../base64_encode/index'
import u15 from '../base64url_decode/index'
import u16 from '../base64url_encode/index'
import u17 from '../base85_decode/index'
import u18 from '../base85_encode/index'
import u19 from '../base91_decode/index'
import u20 from '../base91_encode/index'
import u21 from '../bcrypt_hash/index'
import u22 from '../bcrypt_verify/index'
import u23 from '../binary_decode/index'
import u24 from '../binary_encode/index'
import u25 from '../bit_ops/index'
import u26 from '../blake/index'
import u27 from '../bom/index'
import u28 from '../box_text/index'
import u29 from '../brotli_decompress/index'
import u30 from '../bytes_humanize/index'
import u31 from '../caesar/index'
import u32 from '../case/index'
import u33 from '../char_frequency/index'
import u34 from '../charset_decode/index'
import u35 from '../charset_encode/index'
import u36 from '../checksum/index'
import u37 from '../checksum_verify/index'
import u38 from '../chunk/index'
import u39 from '../cidr/index'
import u40 from '../code_string_escape/index'
import u41 from '../code_string_unescape/index'
import u42 from '../codepoints_decode/index'
import u43 from '../codepoints_encode/index'
import u44 from '../collapse_whitespace/index'
import u45 from '../color_contrast/index'
import u46 from '../color_convert/index'
import u47 from '../columnar_decode/index'
import u48 from '../columnar_encode/index'
import u49 from '../count/index'
import u50 from '../cron_describe/index'
import u51 from '../csv_columns/index'
import u52 from '../csv_delimiter/index'
import u53 from '../csv_normalize_headers/index'
import u54 from '../csv_to_html/index'
import u55 from '../csv_to_json/index'
import u56 from '../csv_to_markdown/index'
import u57 from '../csv_to_sql/index'
import u58 from '../csv_transpose/index'
import u59 from '../curl_build/index'
import u60 from '../curl_parse/index'
import u61 from '../custom_js/index'
import u62 from '../data_uri_build/index'
import u63 from '../data_uri_parse/index'
import u64 from '../date_format/index'
import u65 from '../deflate_compress/index'
import u66 from '../deflate_decompress/index'
import u67 from '../detect_format/index'
import u68 from '../diacritics/index'
import u69 from '../duration_humanize/index'
import u70 from '../entropy/index'
import u71 from '../env_to_json/index'
import u72 from '../escape_html/index'
import u73 from '../extract_preset/index'
import u74 from '../fake_data/index'
import u75 from '../filter_lines_by_length/index'
import u76 from '../format_case/index'
import u77 from '../get_bytes/index'
import u78 from '../grep_lines/index'
import u79 from '../gzip_compress/index'
import u80 from '../gzip_decompress/index'
import u81 from '../hash/index'
import u82 from '../head/index'
import u83 from '../hex_decode/index'
import u84 from '../hex_dump/index'
import u85 from '../hex_encode/index'
import u86 from '../hmac/index'
import u87 from '../html_entity_decode/index'
import u88 from '../html_entity_encode/index'
import u89 from '../html_table_to_csv/index'
import u90 from '../html_to_markdown/index'
import u91 from '../http_headers_build/index'
import u92 from '../http_headers_parse/index'
import u93 from '../ieee754/index'
import u94 from '../indent/index'
import u95 from '../ini_to_json/index'
import u96 from '../initials/index'
import u97 from '../insert_at/index'
import u98 from '../ip_convert/index'
import u99 from '../json_diff/index'
import u100 from '../json_escape/index'
import u101 from '../json_flatten/index'
import u102 from '../json_minify/index'
import u103 from '../json_pretty/index'
import u104 from '../json_schema_validate/index'
import u105 from '../json_sort_keys/index'
import u106 from '../json_to_csv/index'
import u107 from '../json_to_env/index'
import u108 from '../json_to_ini/index'
import u109 from '../json_to_jsonl/index'
import u110 from '../json_to_query_string/index'
import u111 from '../json_to_schema/index'
import u112 from '../json_to_toml/index'
import u113 from '../json_to_typescript/index'
import u114 from '../json_to_xml/index'
import u115 from '../json_to_yaml/index'
import u116 from '../json_unescape/index'
import u117 from '../json_unflatten/index'
import u118 from '../json_validate/index'
import u119 from '../json5_parse/index'
import u120 from '../jsonl_to_json/index'
import u121 from '../jsonpath/index'
import u122 from '../jwt_decode/index'
import u123 from '../jwt_verify/index'
import u124 from '../language_detect/index'
import u125 from '../leet/index'
import u126 from '../length/index'
import u127 from '../line_affix/index'
import u128 from '../line_dedupe/index'
import u129 from '../line_reverse/index'
import u130 from '../line_sort/index'
import u131 from '../lorem_ipsum/index'
import u132 from '../mac_format/index'
import u133 from '../markdown_strip/index'
import u134 from '../markdown_table_format/index'
import u135 from '../markdown_to_csv/index'
import u136 from '../markdown_to_html/index'
import u137 from '../md5/index'
import u138 from '../mime_from_magic/index'
import u139 from '../mime_lookup/index'
import u140 from '../morse_decode/index'
import u141 from '../morse_encode/index'
import u142 from '../msgpack_decode/index'
import u143 from '../msgpack_encode/index'
import u144 from '../multi_replace/index'
import u145 from '../nanoid/index'
import u146 from '../ngram_frequency/index'
import u147 from '../normalize/index'
import u148 from '../normalize_line_endings/index'
import u149 from '../number_base_convert/index'
import u150 from '../number_format/index'
import u151 from '../number_lines/index'
import u152 from '../number_sequence/index'
import u153 from '../number_words/index'
import u154 from '../octal_decode/index'
import u155 from '../octal_encode/index'
import u156 from '../ordinalize/index'
import u157 from '../pad/index'
import u158 from '../password_generator/index'
import u159 from '../pbkdf2/index'
import u160 from '../pluralize_words/index'
import u161 from '../protobuf_decode/index'
import u162 from '../punycode_decode/index'
import u163 from '../punycode_encode/index'
import u164 from '../qr_code/index'
import u165 from '../query_params_normalize/index'
import u166 from '../query_string_to_json/index'
import u167 from '../quoted_printable_decode/index'
import u168 from '../quoted_printable_encode/index'
import u169 from '../rail_fence_decode/index'
import u170 from '../rail_fence_encode/index'
import u171 from '../random_bytes/index'
import u172 from '../random_case/index'
import u173 from '../random_string/index'
import u174 from '../readability/index'
import u175 from '../reading_time/index'
import u176 from '../regex_explain/index'
import u177 from '../regex_extract/index'
import u178 from '../remove_blank_lines/index'
import u179 from '../remove_invisible/index'
import u180 from '../repeat/index'
import u181 from '../replace/index'
import u182 from '../reverse/index'
import u183 from '../reverse_words/index'
import u184 from '../roman_numerals/index'
import u185 from '../rot13/index'
import u186 from '../sed/index'
import u187 from '../semver/index'
import u188 from '../set_operations/index'
import u189 from '../sha3/index'
import u190 from '../shell_quote/index'
import u191 from '../shuffle/index'
import u192 from '../slice/index'
import u193 from '../slug/index'
import u194 from '../smart_quotes/index'
import u195 from '../sort_words_in_line/index'
import u196 from '../split_join/index'
import u197 from '../sql_escape/index'
import u198 from '../sql_format/index'
import u199 from '../sql_minify/index'
import u200 from '../string_distance/index'
import u201 from '../strip_ansi/index'
import u202 from '../strip_chars/index'
import u203 from '../strip_html_tags/index'
import u204 from '../substring_around/index'
import u205 from '../swap_case/index'
import u206 from '../tabs_spaces/index'
import u207 from '../tail/index'
import u208 from '../template_expand/index'
import u209 from '../text_diff/index'
import u210 from '../text_stats/index'
import u211 from '../timestamp_convert/index'
import u212 from '../timestamp_now/index'
import u213 from '../toml_to_json/index'
import u214 from '../tr/index'
import u215 from '../trim/index'
import u216 from '../trim_lines/index'
import u217 from '../truncate/index'
import u218 from '../ulid/index'
import u219 from '../unescape_html/index'
import u220 from '../unicode_escape_decode/index'
import u221 from '../unicode_escape_encode/index'
import u222 from '../unicode_inspect/index'
import u223 from '../unicode_style/index'
import u224 from '../uniq_count/index'
import u225 from '../unwrap/index'
import u226 from '../url_build/index'
import u227 from '../url_decode/index'
import u228 from '../url_encode/index'
import u229 from '../url_parse/index'
import u230 from '../user_agent_parse/index'
import u231 from '../uuid/index'
import u232 from '../validate/index'
import u233 from '../vigenere_decode/index'
import u234 from '../vigenere_encode/index'
import u235 from '../word_frequency/index'
import u236 from '../word_wrap/index'
import u237 from '../xml_escape/index'
import u238 from '../xml_minify/index'
import u239 from '../xml_pretty/index'
import u240 from '../xml_to_json/index'
import u241 from '../xml_unescape/index'
import u242 from '../xor_cipher/index'
import u243 from '../yaml_to_json/index'
import u244 from '../zip_extract/index'
import u245 from '../zip_list/index'

export const STATIC_UTILITIES: Utility[] = [
  u0,
  u1,
  u2,
  u3,
  u4,
  u5,
  u6,
  u7,
  u8,
  u9,
  u10,
  u11,
  u12,
  u13,
  u14,
  u15,
  u16,
  u17,
  u18,
  u19,
  u20,
  u21,
  u22,
  u23,
  u24,
  u25,
  u26,
  u27,
  u28,
  u29,
  u30,
  u31,
  u32,
  u33,
  u34,
  u35,
  u36,
  u37,
  u38,
  u39,
  u40,
  u41,
  u42,
  u43,
  u44,
  u45,
  u46,
  u47,
  u48,
  u49,
  u50,
  u51,
  u52,
  u53,
  u54,
  u55,
  u56,
  u57,
  u58,
  u59,
  u60,
  u61,
  u62,
  u63,
  u64,
  u65,
  u66,
  u67,
  u68,
  u69,
  u70,
  u71,
  u72,
  u73,
  u74,
  u75,
  u76,
  u77,
  u78,
  u79,
  u80,
  u81,
  u82,
  u83,
  u84,
  u85,
  u86,
  u87,
  u88,
  u89,
  u90,
  u91,
  u92,
  u93,
  u94,
  u95,
  u96,
  u97,
  u98,
  u99,
  u100,
  u101,
  u102,
  u103,
  u104,
  u105,
  u106,
  u107,
  u108,
  u109,
  u110,
  u111,
  u112,
  u113,
  u114,
  u115,
  u116,
  u117,
  u118,
  u119,
  u120,
  u121,
  u122,
  u123,
  u124,
  u125,
  u126,
  u127,
  u128,
  u129,
  u130,
  u131,
  u132,
  u133,
  u134,
  u135,
  u136,
  u137,
  u138,
  u139,
  u140,
  u141,
  u142,
  u143,
  u144,
  u145,
  u146,
  u147,
  u148,
  u149,
  u150,
  u151,
  u152,
  u153,
  u154,
  u155,
  u156,
  u157,
  u158,
  u159,
  u160,
  u161,
  u162,
  u163,
  u164,
  u165,
  u166,
  u167,
  u168,
  u169,
  u170,
  u171,
  u172,
  u173,
  u174,
  u175,
  u176,
  u177,
  u178,
  u179,
  u180,
  u181,
  u182,
  u183,
  u184,
  u185,
  u186,
  u187,
  u188,
  u189,
  u190,
  u191,
  u192,
  u193,
  u194,
  u195,
  u196,
  u197,
  u198,
  u199,
  u200,
  u201,
  u202,
  u203,
  u204,
  u205,
  u206,
  u207,
  u208,
  u209,
  u210,
  u211,
  u212,
  u213,
  u214,
  u215,
  u216,
  u217,
  u218,
  u219,
  u220,
  u221,
  u222,
  u223,
  u224,
  u225,
  u226,
  u227,
  u228,
  u229,
  u230,
  u231,
  u232,
  u233,
  u234,
  u235,
  u236,
  u237,
  u238,
  u239,
  u240,
  u241,
  u242,
  u243,
  u244,
  u245,
]
